=== arianne/stendhal/data/conf/creatures.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>


<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                   elementFormDefault="qualified">

	<xsd:element name="creatures" type="Creatures"/>

	<xsd:element name="creature" type="Creature"/>


	<xsd:complexType name="Creatures">
		<xsd:sequence>
			<xsd:element name="creature" type="Creature" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="Creature">
		<xsd:sequence>
			<xsd:element name="type" type="Type" minOccurs="1"/>
			<xsd:element name="hidden" type="xsd:string" minOccurs="0"/>
			<xsd:element name="description" type="xsd:string" minOccurs="0"/>
			<xsd:element name="attributes" type="Attributes" minOccurs="1"/>
			<xsd:element name="level" type="Level" minOccurs="1"/>
			<xsd:element name="experience" type="Experience" minOccurs="1"/>
			<xsd:element name="drops" type="Drops" minOccurs="0"/>
			<xsd:element name="slots" type="Slots" minOccurs="0"/>
			<xsd:element name="equips" type="Equips" minOccurs="0"/>
			<xsd:element name="ai" type="Ai" minOccurs="1"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Item">
		<xsd:attribute name="value" type="xsd:string"/>
		<xsd:attribute name="quantity" type="xsd:string"/>
		<xsd:attribute name="probability" type="xsd:nonNegativeInteger"/>
	</xsd:complexType>

	<xsd:complexType name="Drops">
		<xsd:sequence>
			<xsd:element name="item" type="Item" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Attributes">
		<xsd:sequence>
			<xsd:element name="atk" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="def" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="hp" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="speed" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:decimal"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="size" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="noise" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Ai">
		<xsd:sequence>
			<xsd:element name="says" type="Says" minOccurs="0"/>
			<xsd:element name="profile" type="Profile" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Says">
		<xsd:sequence>
			<xsd:element name="noise" type="Noise" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Noise">
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Profile">
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="params" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Type">
		<xsd:attribute name="class" type="xsd:string"/>
		<xsd:attribute name="subclass" type="xsd:string"/>
		<xsd:attribute name="tileid" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Level">
		<xsd:attribute name="value" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="Experience">
		<xsd:attribute name="value" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="Slots">
		<xsd:sequence>
			<xsd:element name="slot" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Equips">
		<xsd:sequence>
			<xsd:element name="head" type="xsd:string" minOccurs="0"/>
			<xsd:element name="lhand" type="xsd:string" minOccurs="0"/>
			<xsd:element name="rhand" type="xsd:string" minOccurs="0"/>
			<xsd:element name="body" type="xsd:string" minOccurs="0"/>
			<xsd:element name="legs" type="xsd:string" minOccurs="0"/>
			<xsd:element name="feet" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== arianne/stendhal/data/conf/creatures/oni.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd">

  <!-- START: oni -->

  <creature name="oni warrior">
    <type class="oni" subclass="oni_warrior" tileid="oni.png:0"/>
    <description>You see an oni warrior. His purple skin colour should not lull you into a false sense of security!</description>
    <attributes>
      <atk value="499"/>
      <def value="77"/>
      <hp value="500"/>
      <speed value="0.9"/>
      <size value="1,1"/>
    </attributes>
    <level value="67"/>
    <experience value="3660"/>
    <respawn value="2000"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[10,50]" probability="90.0"/>
      <item value="shadow legs" quantity="[1,1]" probability="0.8"/>
      <item value="shadow boots" quantity="[1,1]" probability="1.0"/>
      <item value="pie" quantity="[1,2]" probability="5.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="oni archer">
    <type class="oni" subclass="oni_archer" tileid="oni.png:1"/>
    <description>You see an oni archer. His arrows will follow you everywhere for protecting his queen!</description>
    <attributes>
      <atk value="511"/>
      <ratk value="511"/>
      <def value="77"/>
      <hp value="600"/>
      <speed value="0.7"/>
      <size value="1,1"/>
    </attributes>
    <level value="72"/>
    <experience value="4000"/>
    <respawn value="2300"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[10,70]" probability="100.0"/>
      <item value="golden legs" quantity="[1,1]" probability="2.0"/>
      <item value="golden arrow" quantity="[8,15]" probability="5.0"/>
      <item value="golden boots" quantity="[1,1]" probability="2.0"/>
    </drops>
    <equips>
      <slot name="lhand" item="power arrow" quantity="10000"/>
      <slot name="rhand" item="composite bow" quantity="1"/>
    </equips>
    <ai>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="archer"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="oni priest">
    <type class="oni" subclass="oni_priest" tileid="oni.png:2"/>
    <description>You see a mysterious oni priest, uttering strange incantations.</description>
    <attributes>
      <atk value="547"/>
      <def value="76"/>
      <hp value="680"/>
      <speed value="0.8"/>
      <size value="1,1"/>
    </attributes>
    <level value="77"/>
    <experience value="5290"/>
    <respawn value="2590"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="greater potion" quantity="[1,2]" probability="50.0"/>
      <item value="money" quantity="[10,40]" probability="100.0"/>
      <item value="shadow boots" quantity="[1,1]" probability="0.5"/>
      <item value="chaos cloak" quantity="[1,1]" probability="0.050"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="heal" params="5,40"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="oni king">
    <type class="oni" subclass="oni_king" tileid="oni.png:3"/>
    <description>You see the oni king. His power leads brave oni troops around his kingdom.</description>
    <attributes>
      <atk value="714"/>
      <def value="93"/>
      <hp value="1200"/>
      <speed value="0.8"/>
      <size value="1,1"/>
    </attributes>
    <level value="109"/>
    <experience value="14000"/>
    <respawn value="5300"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[10,70]" probability="100.0"/>
      <item value="greater potion" quantity="[1,1]" probability="30.0"/>
      <item value="gold bar" quantity="[1,1]" probability="3.0"/>
      <item value="horned golden helmet" quantity="[1,1]" probability="1.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="Revere me, the Oni King!"/>
      </says>
      <profile name="offensive"/>
      <profile name="human"/>
    </ai>
  </creature>

  <creature name="oni queen">
    <type class="oni" subclass="oni_queen" tileid="oni.png:4"/>
    <description>You see the oni queen. She supports her husband and takes an eye onto their kingdom while he conquers new land and fights on battlefields.</description>
    <attributes>
      <atk value="737"/>
      <def value="98"/>
      <hp value="1200"/>
      <speed value="0.8"/>
      <size value="1,1"/>
    </attributes>
    <level value="118"/>
    <experience value="17000"/>
    <respawn value="6200"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[10,50]" probability="100.0"/>
      <item value="greater potion" quantity="[1,2]" probability="30.0"/>
      <item value="gold bar" quantity="[1,2]" probability="5.0"/>
      <item value="golden cloak" quantity="[1,1]" probability="1.0"/>
      <item value="liberty helmet" quantity="[1,1]" probability="0.1"/>
      <item value="aventail" quantity="[1,1]" probability="10.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="You must bow before the Oni Queen."/>
      </says>
      <profile name="offensive"/>
      <profile name="human"/>
    </ai>
  </creature>

  <!-- END: oni -->

</creatures>

=== arianne/stendhal/data/conf/creatures/giant_animal.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd ">
    
 <creature name="giantrat">
    <type class="giant_animal" subclass="giantrat" tileid="giant_animal.png:1"/>
    <description>You see a giant rat. It seems like it survived from an experiment which went wrong.</description>
    <attributes>
      <atk value="173"/>
      <def value="30"/>
      <hp value="110"/>
      <speed value="1.0"/>
      <size value="2,2"/>
    </attributes>
    <level value="15"/>
    <experience value="180"/>
    <respawn value="1230"/>
    <corpse name="huge_animal" harmless="tail_rodent_large" width="2" height="2" />
    <drops>
      <item value="money" quantity="[7,20]" probability="100.0"/>
      <item value="cheese" quantity="[3,7]" probability="80.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
      	<sound value="bobcat-1"/>
      	<sound value="leopard-11"/>
      </says>
      <profile name="brave"/>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="heal" params="5,150"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
   <creature name="crocodile">
    <type class="giant_animal" subclass="crocodile" tileid="giant_animal.png:0"/>
    <description>You see a crocodile, it arises from the deep waters in the rivers.</description>
    <attributes>
      <atk value="172"/>
      <def value="30"/>
      <hp value="110"/>
      <speed value="1.0"/>
      <size value="2,2"/>
    </attributes>
    <level value="15"/>
    <experience value="180"/>
    <respawn value="1230"/>
    <corpse name="huge_animal" width="2" height="2"/>
    <drops>
      <item value="money" quantity="[3,12]" probability="100.0"/>
      <item value="meat" quantity="[3,7]" probability="80.0"/>
      <item value="ham" quantity="[2,5]" probability="50.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="Rrrrrrrrr"/>
        <sound value="alligator-1" />
      </says>
      <profile name="brave"/>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="heal" params="5,150"/>
      <profile name="patrolling"/>
    </ai>
  </creature>  
  
  <!-- used to be in giant human folder which is why the tiled image is different -->
  <creature name="dwarf golem">
    <type class="giant_animal" subclass="dwarf_golem" tileid="giant_human.png:5"/>
    <description>You see a dwarf golem. A long time ago a dwarf got turned into a big rock by some mystical forces. To save their friend the other dwarves created a golem out of this rock! From this day the dwarf golem lives together with them.</description>
    <attributes>
      <atk value="939"/>
      <def value="99"/>
      <hp value="2700"/>
      <speed value="1.0"/>
      <size value="3,2"/>
    </attributes>
    <level value="170"/>
    <experience value="50800"/>
    <respawn value="16000"/>
    <corpse name="giant_humanoid" width="2" height="2"/>
    <drops>
      <item value="money" quantity="[30,150]" probability="100.0"/>
      <item value="greater potion" quantity="[1,2]" probability="50.0"/>
      <item value="stone armor" quantity="[1,1]" probability="2.0"/>
      <item value="durin axe" quantity="[1,1]" probability="0.25"/>
      <item value="magic twoside axe" quantity="[1,1]" probability="1.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="brave"/>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="heal" params="5,50"/>
    </ai>
  </creature>
  
</creatures>

=== arianne/stendhal/data/conf/creatures/albino_elf.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd ">
  
  <creature name="albino elf archer">
    <type class="albino_elf" subclass="albino_elf_archer" tileid="albino_elf.png:0"/>
    <description>You see an albino elf archer. He is so sharp-eyed that he could hit a bee from a distance of 100 meters.</description>
    <attributes>
      <atk value="345"/>
      <def value="94"/>
      <hp value="150"/>
      <speed value="0.7"/>
      <size value="1,1"/>
    </attributes>
    <level value="42"/>
    <experience value="960"/>
    <respawn value="1630"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[10,30]" probability="90.0"/>
      <item value="studded armor" quantity="[1,1]" probability="2.0"/>
      <item value="steel arrow" quantity="[5,15]" probability="10.0"/>
      <item value="wooden bow" quantity="[1,1]" probability="2.0"/>
    </drops>
    <equips>
      <slot name="lhand" item="steel arrow" quantity="10000"/>
      <slot name="rhand" item="wooden bow" quantity="1"/>
    </equips>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="archer"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
  <creature name="albino elf king">
    <type class="albino_elf" subclass="albino_elf_king" tileid="albino_elf.png:1"/>
    <description>You see an albino elf king. He is the patriarch of albino elves and won countless of battles with his powerful albino elf army.</description>
    <attributes>
      <atk value="461"/>
      <def value="53"/>
      <hp value="675"/>
      <speed value="0.8"/>
      <size value="1,1"/>
    </attributes>
    <level value="60"/>
    <experience value="2800"/>
    <respawn value="1900"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[30,60]" probability="100.0"/>
      <item value="shadow armor" quantity="[1,1]" probability="0.5"/>
      <item value="shadow boots" quantity="[1,1]" probability="1.0"/>
      <item value="shadow helmet" quantity="[1,1]" probability="0.35"/>
      <item value="great sword" quantity="[1,1]" probability="0.5"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="heal" params="5,50"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
  <creature name="albino elf magician">
    <type class="albino_elf" subclass="albino_elf_magician" tileid="albino_elf.png:2"/>
    <description>You see an albino elf magician. He knows all the secrets of magic. You'd be better to not let him unleash his full power!</description>
    <attributes>
      <atk value="432"/>
      <def value="58"/>
      <hp value="500"/>
      <speed value="0.7"/>
      <size value="1,1"/>
    </attributes>
    <level value="55"/>
    <experience value="2210"/>
    <respawn value="1600"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="elf cloak" quantity="[1,1]" probability="2.5"/> 
      <item value="greater potion" quantity="[1,2]" probability="20.0"/>
      <item value="money" quantity="[10,70]" probability="100.0"/>
      <item value="empty scroll" quantity="[1,2]" probability="8.0"/>
      <item value="scroll eraser" quantity="[1,1]" probability="0.4"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="heal" params="10,60"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
  <creature name="albino elf queen">
    <type class="albino_elf" subclass="albino_elf_queen" tileid="albino_elf.png:3"/>
    <description>You see an albino elf queen. She is the matriarch of the albino elf race and she will do everything to protect it.</description>
    <attributes>
      <atk value="454"/>
      <def value="48"/>
      <hp value="700"/>
      <speed value="0.9"/>
      <size value="1,1"/>
    </attributes>
    <level value="58"/>
    <experience value="2700"/>
    <respawn value="1800"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[30,60]" probability="100.0"/>
      <item value="shadow boots" quantity="[1,1]" probability="0.5"/>
      <item value="drow sword" quantity="[1,1]" probability="0.01"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="heal" params="10,30"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
  <creature name="albino elf swordsman">
    <type class="albino_elf" subclass="albino_elf_swordsman" tileid="albino_elf.png:4"/>
    <description>You see an albino elf swordsman who is a professional in using swords. He can attack you from behind in a blink of an eye.</description>
    <attributes>
      <atk value="330"/>
      <def value="57"/>
      <hp value="250"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="38"/>
    <experience value="920"/>
    <respawn value="1460"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[4,40]" probability="100.0"/>
      <item value="golden armor" quantity="[1,1]" probability="0.5"/>
      <item value="golden boots" quantity="[1,1]" probability="0.5"/>
      <item value="golden helmet" quantity="[1,1]" probability="0.35"/>
      <item value="broadsword" quantity="[1,1]" probability="1.5"/>
      <item value="elf cloak" quantity="[1,1]" probability="1.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
</creatures>

=== arianne/stendhal/data/conf/creatures/mutant.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd ">

  <creature name="poison shroom">
    <type class="mutant" subclass="poison_shroom_small" tileid="mutant.png:6"/>
    <description></description>
    <attributes>
      <atk value="1"/>
      <def value="1"/>
      <hp value="1"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="1"/>
    <experience value="1"/>
    <respawn value="1000"/>
    <corpse name="humanoid"/>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
      <profile name="strategy" params=",outfit_changer(hand_to_hand;poison_shroom_small;poison_shroom),"/>
    </ai>
  </creature>

</creatures>

=== arianne/stendhal/data/conf/creatures/human_mithrilbourgh.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd">

  <creature name="mithrilbourgh soldier">
    <type class="human" subclass="mithril_soldier" tileid="human_soldier.png:2"/>
    <description/>
    <attributes>
      <atk value="490"/>
      <def value="78"/>
      <hp value="500"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="64"/>
    <experience value="3260"/>
    <respawn value="1960"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[5,33]" probability="100.0"/>
      <item value="stone boots" quantity="[1,1]" probability="1.5"/>
      <item value="broadsword" quantity="[1,1]" probability="1.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="mithrilbourgh archer">
    <type class="human" subclass="mithril_archer" tileid="human_soldier.png:0"/>
    <description/>
    <attributes>
      <atk value="487"/>
      <ratk value="487"/>
      <def value="76"/>
      <hp value="540"/>
      <speed value="0.7"/>
      <size value="1,1"/>
    </attributes>
    <level value="68"/>
    <experience value="3820"/>
    <respawn value="2140"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[5,53]" probability="100.0"/>
      <item value="golden arrow" quantity="[5,20]" probability="5.0"/>
      <item value="composite bow" quantity="[1,1]" probability="0.5"/>
    </drops>
    <equips>
      <slot name="lhand" item="golden arrow" quantity="10000"/>
      <slot name="rhand" item="composite bow" quantity="1"/>
    </equips>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="archer"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="mithrilbourgh knight">
    <type class="human" subclass="mithril_knight" tileid="human_soldier.png:5"/>
    <description/>
    <attributes>
      <atk value="523"/>
      <def value="78"/>
      <hp value="595"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="71"/>
    <experience value="4280"/>
    <respawn value="2290"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[5,33]" probability="100.0"/>
      <item value="dwarvish armor" quantity="[1,1]" probability="1.5"/>
      <item value="stone armor" quantity="[1,1]" probability="0.08"/>
      <item value="chaos boots" quantity="[1,1]" probability="0.08"/>
      <item value="horned golden helmet" quantity="[1,1]" probability="0.5"/>
      <item value="great sword" quantity="[1,1]" probability="0.05"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
    </ai>
  </creature>

  <creature name="mithrilbourgh elite archer">
    <type class="human" subclass="mithril_elite_archer" tileid="human_soldier.png:3"/>
    <description/>
    <attributes>
      <atk value="500"/>
      <ratk value="500"/>
      <def value="73"/>
      <hp value="608"/>
      <speed value="0.8"/>
      <size value="1,1"/>
    </attributes>
    <level value="72"/>
    <experience value="4450"/>
    <respawn value="2350"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[5,33]" probability="100.0"/>
      <item value="power arrow" quantity="[1,5]" probability="5.0"/>
      <item value="golden arrow" quantity="[3,15]" probability="10.0"/>
      <item value="composite bow" quantity="[1,1]" probability="2.5"/>
    </drops>
    <equips>
      <slot name="lhand" item="power arrow" quantity="10000"/>
      <slot name="rhand" item="composite bow" quantity="1"/>
    </equips>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="archer"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="mithrilbourgh sergeant">
    <type class="human" subclass="mithril_sergeant" tileid="human_soldier.png:7"/>
    <description/>
    <attributes>
      <atk value="547"/>
      <def value="80"/>
      <hp value="650"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="76"/>
    <experience value="5140"/>
    <respawn value="2570"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[5,63]" probability="100.0"/>
      <item value="stone armor" quantity="[1,1]" probability="0.1"/>
      <item value="chaos boots" quantity="[1,1]" probability="0.7"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
      <profile name="attack weakest"/>
    </ai>
  </creature>

  <creature name="mithrilbourgh lieutenant">
    <type class="human" subclass="mithril_lieutenant" tileid="human_soldier.png:6"/>
    <description/>
    <attributes>
      <atk value="577"/>
      <def value="80"/>
      <hp value="760"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="83"/>
    <experience value="6540"/>
    <respawn value="3010"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[5,63]" probability="100.0"/>
      <item value="stone armor" quantity="[1,1]" probability="0.1"/>
      <item value="chaos boots" quantity="[1,1]" probability="1.0"/>
      <item value="chaos helmet" quantity="[1,1]" probability="0.4"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="attack weakest"/>
    </ai>
  </creature>

  <creature name="mithrilbourgh colonel">
    <type class="human" subclass="mithril_colonel" tileid="human_soldier.png:1"/>
    <description/>
    <attributes>
      <atk value="610"/>
      <def value="82"/>
      <hp value="860"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="89"/>
    <experience value="7930"/>
    <respawn value="3450"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[5,95]" probability="100.0"/>
      <item value="stone armor" quantity="[1,1]" probability="0.7"/>
      <item value="chaos boots" quantity="[1,1]" probability="1.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
      <profile name="attack weakest"/>
    </ai>
  </creature>

  <creature name="mithrilbourgh wizard">
    <type class="human" subclass="mithril_wizard" tileid="human_soldier.png:8"/>
    <description/>
    <attributes>
      <atk value="634"/>
      <def value="80"/>
      <hp value="911"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="92"/>
    <experience value="8700"/>
    <respawn value="3690"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[5,93]" probability="100.0"/>
      <item value="empty scroll" quantity="[1,2]" probability="10.0"/>
      <item value="scroll eraser" quantity="[1,1]" probability="1.0"/>
    </drops>
    <equips>
    </equips>
    <abilities>
      <susceptibility type="dark" value="0.9"/>
      <susceptibility type="light" value="0.9"/>
    </abilities>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
    </ai>
  </creature>

  <creature name="mithrilbourgh general">
    <type class="human" subclass="mithril_general" tileid="human_soldier.png:4"/>
    <description>You see a mithrilbourgh general. Some call him Hawkeyes. He cast his gaze over the city walls and saw you coming from miles away.</description>
    <attributes>
      <atk value="624"/>
      <def value="83"/>
      <hp value="960"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="95"/>
    <experience value="9520"/>
    <respawn value="3940"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[5,100]" probability="100.0"/>
      <item value="ice armor" quantity="[1,1]" probability="0.1"/>
      <item value="chaos boots" quantity="[1,1]" probability="2.0"/>
      <item value="shadow cloak" quantity="[1,1]" probability="1.0"/>
      <item value="magic plate shield" quantity="[1,1]" probability="1.0"/>
      <item value="ice sword" quantity="[1,1]" probability="0.1"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="attack weakest"/>
    </ai>
  </creature>

</creatures>
