=== arianne/stendhal/data/conf/creatures.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>


<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                   elementFormDefault="qualified">

	<xsd:element name="creatures" type="Creatures"/>

	<xsd:element name="creature" type="Creature"/>


	<xsd:complexType name="Creatures">
		<xsd:sequence>
			<xsd:element name="creature" type="Creature" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="Creature">
		<xsd:sequence>
			<xsd:element name="type" type="Type" minOccurs="1"/>
			<xsd:element name="hidden" type="xsd:string" minOccurs="0"/>
			<xsd:element name="description" type="xsd:string" minOccurs="0"/>
			<xsd:element name="attributes" type="Attributes" minOccurs="1"/>
			<xsd:element name="level" type="Level" minOccurs="1"/>
			<xsd:element name="experience" type="Experience" minOccurs="1"/>
			<xsd:element name="drops" type="Drops" minOccurs="0"/>
			<xsd:element name="slots" type="Slots" minOccurs="0"/>
			<xsd:element name="equips" type="Equips" minOccurs="0"/>
			<xsd:element name="ai" type="Ai" minOccurs="1"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Item">
		<xsd:attribute name="value" type="xsd:string"/>
		<xsd:attribute name="quantity" type="xsd:string"/>
		<xsd:attribute name="probability" type="xsd:nonNegativeInteger"/>
	</xsd:complexType>

	<xsd:complexType name="Drops">
		<xsd:sequence>
			<xsd:element name="item" type="Item" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Attributes">
		<xsd:sequence>
			<xsd:element name="atk" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="def" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="hp" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="speed" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:decimal"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="size" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="noise" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Ai">
		<xsd:sequence>
			<xsd:element name="says" type="Says" minOccurs="0"/>
			<xsd:element name="profile" type="Profile" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Says">
		<xsd:sequence>
			<xsd:element name="noise" type="Noise" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Noise">
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Profile">
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="params" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Type">
		<xsd:attribute name="class" type="xsd:string"/>
		<xsd:attribute name="subclass" type="xsd:string"/>
		<xsd:attribute name="tileid" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Level">
		<xsd:attribute name="value" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="Experience">
		<xsd:attribute name="value" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="Slots">
		<xsd:sequence>
			<xsd:element name="slot" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Equips">
		<xsd:sequence>
			<xsd:element name="head" type="xsd:string" minOccurs="0"/>
			<xsd:element name="lhand" type="xsd:string" minOccurs="0"/>
			<xsd:element name="rhand" type="xsd:string" minOccurs="0"/>
			<xsd:element name="body" type="xsd:string" minOccurs="0"/>
			<xsd:element name="legs" type="xsd:string" minOccurs="0"/>
			<xsd:element name="feet" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== arianne/stendhal/data/conf/creatures/farm_animal.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd ">
    
  <creature name="chick">
    <type class="farm_animal" subclass="chick" tileid="farm_animal.png:2"/>
    <description>You see a little chick, it doesn't like to be away from its mother.</description>
    <attributes>
      <atk value="32"/>
      <def value="7"/>
      <hp value="25"/>
      <speed value="0.5"/>
      <size value="1,1"/>
    </attributes>
    <level value="1"/>
    <experience value="5"/>
    <respawn value="900"/>
    <corpse name="small_winged" harmless="feathered" />
    <drops>
      <item value="chicken" quantity="[1,1]" probability="70.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="peep peep"/>
        <noise state="idle follow fight" value="peep peep peep"/>
        <sound value="chicken-chick-1" />
        <sound value="chicken-chick-2" />
      </says>
      <profile name="animal"/>
      <profile name="patrolling"/>
      <profile name="non offensive"/>
      <profile name="coward"/>
    </ai>
  </creature>

  <creature name="piglet">
    <type class="farm_animal" subclass="piglet" tileid="farm_animal.png:9"/>
    <description>You see a piglet, a bit dirty.</description>
    <attributes>
      <atk value="31"/>
      <def value="7"/>
      <hp value="25"/>
      <speed value="0.6"/>
      <size value="1,1"/>
    </attributes>
    <level value="1"/>
    <experience value="5"/>
    <respawn value="900"/>
    <corpse name="animal"/>
    <drops>
      <item value="ham" quantity="[1,1]" probability="70.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="oink"/>
        <noise state="idle follow fight" value="oink oink"/>
        <noise state="idle follow fight" value="shnuffle"/>
        <sound value="pig-3" />
      </says>
      <profile name="animal"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
  
  <creature name="mother hen">
    <type class="farm_animal" subclass="hen" tileid="farm_animal.png:6"/>
    <description>You see a mother hen, she will probably hurt you if you touch her sons.</description>
    <attributes>
      <atk value="29"/>
      <def value="6"/>
      <hp value="25"/>
      <speed value="0.7"/>
      <size value="1,1"/>
    </attributes>
    <level value="1"/>
    <experience value="5"/>
    <respawn value="900"/>
    <corpse name="small_winged" harmless="feathered" />
    <drops>
      <item value="chicken" quantity="[1,2]" probability="70.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="peep peep"/>
        <noise state="idle follow fight" value="peep peep peep"/>
        <sound value="chicken-1"/>
      </says>
      <profile name="animal"/>
      <profile name="patrolling"/>
      <profile name="non offensive"/>
    </ai>
  </creature>
  
   <creature name="ram">
    <type class="farm_animal" subclass="ram" tileid="farm_animal.png:10"/>
    <description>You see a ram, maybe you are able to shear it?</description>
    <attributes>
      <atk value="52"/>
      <def value="7"/>
      <hp value="50"/>
      <speed value="0.5"/>
      <size value="1,1"/>
    </attributes>
    <level value="2"/>
    <experience value="20"/>
    <respawn value="900"/>
    <corpse name="animal"/>
    <drops>
      <item value="meat" quantity="[1,1]" probability="40.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="Baaaaaa"/>
      </says>
      <profile name="animal"/>
      <profile name="offensive"/>
    </ai>
  </creature>
  
   <creature name="beaver">
    <type class="farm_animal" subclass="beaver" tileid="farm_animal.png:0"/>
    <description>You see a beaver. It likes to build dams in the river.</description>
    <attributes>
      <atk value="53"/>
      <def value="8"/>
      <hp value="35"/>
      <speed value="0.6"/>
      <size value="1,1"/>
    </attributes>
    <level value="2"/>
    <experience value="20"/>
    <respawn value="900"/>
    <corpse name="animal"/>
    <drops>
      <item value="meat" quantity="[1,2]" probability="80.0"/>
      <item value="wood" quantity="[1,2]" probability="20.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="cow">
    <type class="farm_animal" subclass="cow" tileid="farm_animal.png:3"/>
    <description>You see a cow, taste her delicious milk.</description>
    <attributes>
      <atk value="51"/>
      <def value="9"/>
      <hp value="30"/>
      <speed value="0.3"/>
      <size value="1,1"/>
    </attributes>
    <level value="2"/>
    <experience value="20"/>
    <respawn value="900"/>
    <corpse name="animal"/>
    <drops>
      <item value="meat" quantity="[1,2]" probability="80.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="Moooo       moooo           mooooooo"/>
        <noise state="idle follow fight" value="mooooo"/>
        <sound value="cow-1"/>
      </says>
      <profile name="animal"/>
    </ai>
  </creature>

  <creature name="goat">
    <type class="farm_animal" subclass="goat" tileid="farm_animal.png:4"/>
    <description>You see a goat, which is wild and lives in the mountain.</description>
    <attributes>
      <atk value="52"/>
      <def value="9"/>
      <hp value="30"/>
      <speed value="0.3"/>
      <size value="1,1"/>
    </attributes>
    <level value="2"/>
    <experience value="20"/>
    <respawn value="900"/>
    <corpse name="animal"/>
    <drops>
      <item value="meat" quantity="[1,2]" probability="80.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <sound value="goat-1" />
        <sound value="goat-2" />
      </says>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="horse">
    <type class="farm_animal" subclass="horse" tileid="farm_animal.png:7"/>
    <description>You see a horse, don't slap it or it will run away!</description>
    <attributes>
      <atk value="48"/>
      <def value="10"/>
      <hp value="30"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="2"/>
    <experience value="20"/>
    <respawn value="900"/>
    <corpse name="animal"/>
    <drops>
      <item value="meat" quantity="[1,2]" probability="80.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="neigghhh neigghhh"/>
        <sound value="horse-1" />
        <sound value="horse-2" />
      </says>
      <profile name="animal"/>
      <profile name="non offensive"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="white horse">
    <type class="farm_animal" subclass="white_horse" tileid="farm_animal.png:11"/>
    <description>You see a white horse, they love to stay with their brown friends.</description>
    <attributes>
      <atk value="50"/>
      <def value="9"/>
      <hp value="30"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="2"/>
    <experience value="20"/>
    <respawn value="900"/>
    <corpse name="animal"/>
    <drops>
      <item value="meat" quantity="[1,2]" probability="80.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="naayyy"/>
        <sound value="horse-1" />
        <sound value="horse-2" />
      </says>
      <profile name="animal"/>
      <profile name="non offensive"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
   <creature name="bull">
    <type class="farm_animal" subclass="bull" tileid="farm_animal.png:1"/>
    <description>You see a bull, run away!!!</description>
    <attributes>
      <atk value="47"/>
      <def value="9"/>
      <hp value="35"/>
      <speed value="0.9"/>
      <size value="1,1"/>
    </attributes>
    <level value="2"/>
    <experience value="20"/>
    <respawn value="900"/>
    <corpse name="animal"/>
    <drops>
      <item value="meat" quantity="[1,3]" probability="80.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="MOOOOO!!!"/>
        <sound value="cow-2" />
      </says>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="grass snake">
    <type class="farm_animal" subclass="grass_snake" tileid="farm_animal.png:5"/>
    <description>You see a grass snake which is quite dangerous.</description>
    <attributes>
      <atk value="68"/>
      <def value="15"/>
      <hp value="35"/>
      <speed value="0.6"/>
      <size value="1,1"/>
    </attributes>
    <level value="3"/>
    <experience value="30"/>
    <respawn value="900"/>
    <corpse name="small_boneless"/>
    <drops>
      <item value="money" quantity="[2,6]" probability="60.0"/>
      <item value="poison" quantity="[1,1]" probability="10.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="sssSSSsssss..."/>
        <sound value="snake-1"/>
      </says>
      <profile name="poisonous" params="5,poison"/>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
</creatures>

=== arianne/stendhal/data/conf/creatures/golem.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd ">

  <creature name="wooden golem">
    <type class="golem" subclass="wooden_golem" tileid="golem.png:1"/>
    <description>You see a wooden golem. The scroll with ancient words in his head keeps it walking.</description>
    <attributes>
      <atk value="251"/>
      <def value="34"/>
      <hp value="223"/>
      <speed value="0.3"/>
      <size value="1,1"/>
    </attributes>
    <level value="24"/>
    <experience value="370"/>
    <respawn value="1290"/>
    <corpse name="wooden" harmless="wooden" />
    <drops>
      <item value="money" quantity="[5,19]" probability="100.0"/>
      <item value="wood" quantity="[1,2]" probability="15.0"/>
    </drops>
    <equips>
    </equips>
    <abilities>
      <susceptibility type="fire" value="1.2"/>
    </abilities>
    <ai>
      <profile name="brave"/>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="heal" params="5,50"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="stone golem">
    <type class="golem" subclass="stone_golem" tileid="golem.png:0"/>
    <description>You see a stone golem, it exists to protect and nothing else. What was it crafted to protect, and what would one do if it lost it's purpose?</description>
    <attributes>
      <atk value="297"/>
      <def value="85"/>
      <hp value="95"/>
      <speed value="0.6"/>
      <size value="1,1"/>
    </attributes>
    <level value="32"/>
    <experience value="640"/>
    <respawn value="1380"/>
    <corpse name="rock" harmless="rock" />
    <drops>
      <item value="money" quantity="[5,27]" probability="100.0"/>
      <item value="stone cloak" quantity="[1,1]" probability="2.5"/>
      <item value="stone boots" quantity="[1,1]" probability="0.5"/>
    </drops>
    <equips>
    </equips>
    <abilities>
      <susceptibility type="ice" value="0.9"/>
      <susceptibility type="fire" value="0.9"/>
    </abilities>
    <ai>
      <says>
        <sound value="loop-grind-stone-1" />
      </says>
      <profile name="brave"/>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="heal" params="5,50"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
  <creature name="ice golem">
    <type class="golem" subclass="ice_golem" tileid="golem.png:2"/>
    <description>You see an Ice golem. Ice Golems are elementals made out of ice. You should watch out for its icy fists or you might get hurt.</description>
    <attributes>
      <atk value="381"/>
      <def value="53"/>
      <hp value="390"/>
      <speed value="0.6"/>
      <size value="1,1"/>
    </attributes>
    <level value="45"/>
    <experience value="1360"/>
    <respawn value="1620"/>
    <corpse name="puddle_light_blue"/>
    <drops>
      <item value="money" quantity="[5,27]" probability="100.0"/>
      <item value="snowball" quantity="[1,4]" probability="75"/>
      <item value="ice sword" quantity="[1,1]" probability="0.05"/>
      <item value="ice armor" quantity="[1,1]" probability="0.005"/>
    </drops>
    <equips>
    </equips>
    <abilities>
      <damage type="ice"/>
      <susceptibility type="ice" value="0.5"/>
      <susceptibility type="fire" value="1.5"/>
    </abilities>
    <ai>
      <profile name="brave"/>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="heal" params="5,50"/>
      <profile name="patrolling"/>
    </ai>
  </creature>    
   
</creatures>

=== arianne/stendhal/data/conf/creatures/gargoyle.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd ">
    
  <creature name="gargoyle">
    <type class="gargoyle" subclass="gargoyle" tileid="gargoyle.png:2"/>
    <description>You see a gargoyle, You should think that it is a statue, but no, it is alive!</description>
    <attributes>
      <atk value="98"/>
      <def value="16"/>
      <hp value="70"/>
      <speed value="0.9"/>
      <size value="1,1"/>
    </attributes>
    <level value="6"/>
    <experience value="60"/>
    <respawn value="1200"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[2,10]" probability="90.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
      	<sound value="hyena-1"/>
      	<sound value="hyena-2"/>
      	<sound value="hyena-3"/>
      </says>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
    </ai>
  </creature>
  
  <creature name="elder gargoyle">
    <type class="gargoyle" subclass="elder_gargoyle" tileid="gargoyle.png:1"/>
    <description>You see an elder gargoyle, it is wise...</description>
    <attributes>
      <atk value="114"/>
      <def value="16"/>
      <hp value="100"/>
      <speed value="0.4"/>
      <size value="1,1"/>
    </attributes>
    <level value="8"/>
    <experience value="80"/>
    <respawn value="1200"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[4,12]" probability="90.0"/>
      <item value="mace" quantity="[1,1]" probability="30.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <sound value="loop-grind-stone-1" />
      </says>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
    </ai>
  </creature>
  
  <creature name="dark gargoyle">
    <type class="gargoyle" subclass="dark_gargoyle" tileid="gargoyle.png:0"/>
    <description>You see a dark gargoyle, do you feel the fear?</description>
    <attributes>
      <atk value="134"/>
      <def value="22"/>
      <hp value="93"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="10"/>
    <experience value="110"/>
    <respawn value="1210"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[4,17]" probability="90.0"/>
      <item value="chain armor" quantity="[1,1]" probability="3.0"/>
      <item value="enhanced chainmail" quantity="[1,1]" probability="0.05"/>
      <item value="enhanced mace" quantity="[1,1]" probability="5.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
    </ai>
  </creature>  
  
  <creature name="venom gargoyle">
    <type class="gargoyle" subclass="venom_gargoyle" tileid="gargoyle.png:3"/>
    <description>You see a venom gargoyle, a hideous and poisonous creature.</description>
    <attributes>
      <atk value="188"/>
      <def value="61"/>
      <hp value="55"/>
      <speed value="0.9"/>
      <size value="1,1"/>
    </attributes>
    <level value="16"/>
    <experience value="200"/>
    <respawn value="1230"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[10,25]" probability="90.0"/>
      <item value="enhanced chainmail" quantity="[1,1]" probability="10.0"/>
      <item value="scale armor" quantity="[1,1]" probability="2.0"/>
      <item value="iron scale armor" quantity="[1,1]" probability="0.4"/>
      <item value="poison" quantity="[1,1]" probability="15.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="poisonous" params="15,poison"/>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature> 
  
</creatures>

=== arianne/stendhal/data/conf/creatures/rodent.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd">

  <creature name="mouse">
    <type class="rodent" subclass="mouse" tileid="rodent.png:5"/>
    <description>You see a small mouse that seems to be very hungry.</description>
    <attributes>
      <atk value="8"/>
      <def value="3"/>
      <hp value="20"/>
      <speed value="0.5"/>
      <size value="1,1"/>
    </attributes>
    <level value="0"/>
    <experience value="5"/>
    <respawn value="900"/>
    <corpse name="small_animal" harmless="rodent_small"/>
    <drops>
      <item value="cheese" quantity="[1,2]" probability="100.0"/>
     </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="squeak... squeak!"/>
        <sound value="mouse-2"/>
      </says>
      <profile name="animal"/>
      <profile name="coward"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="rat">
    <type class="rodent" subclass="rat" tileid="rodent.png:1"/>
    <description>You see a small rat that seems to be extremely hungry.</description>
    <attributes>
      <atk value="8"/>
      <def value="3"/>
      <hp value="20"/>
      <speed value="0.5"/>
      <size value="1,1"/>
    </attributes>
    <level value="0"/>
    <experience value="5"/>
    <respawn value="900"/>
    <corpse name="small_animal" harmless="rodent_small"/>
    <drops>
      <item value="cheese" quantity="[1,1]" probability="50.0"/>
      <item value="money" quantity="[1,3]" probability="70.0"/>
      <item value="club" quantity="[1,1]" probability="5.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="Squeak! Squeak!"/>
        <sound value="rat-squeak-01"/>
        <sound value="rat-squeak-02"/>
        <sound value="rat-squeak-03"/>
      </says>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="stupid coward"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="caverat">
    <type class="rodent" subclass="caverat" tileid="rodent.png:0"/>
    <description>You see a caverat which is dirty and loves the dungeons.</description>
    <attributes>
      <atk value="34"/>
      <def value="6"/>
      <hp value="30"/>
      <speed value="0.5"/>
      <size value="1,1"/>
    </attributes>
    <level value="1"/>
    <experience value="10"/>
    <respawn value="900"/>
    <corpse name="small_animal" harmless="rodent_small"/>
    <drops>
      <item value="money" quantity="[1,6]" probability="90.0"/>
      <item value="cheese" quantity="[1,2]" probability="60.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <sound value="rat-squeak-01"/>
        <sound value="rat-squeak-02"/>
        <sound value="rat-squeak-03"/>
      </says>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="coward"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="venomrat">
    <type class="rodent" subclass="venomrat" tileid="rodent.png:3"/>
    <description>You see a venomrat, extremely poisonous.</description>
    <attributes>
      <atk value="89"/>
      <def value="14"/>
      <hp value="70"/>
      <speed value="0.9"/>
      <size value="1,1"/>
    </attributes>
    <level value="5"/>
    <experience value="50"/>
    <respawn value="1200"/>
    <corpse name="small_animal" harmless="rodent_small"/>
    <drops>
      <item value="money" quantity="[3,7]" probability="100.0"/>
      <item value="cheese" quantity="[1,3]" probability="50.0"/>
      <item value="greater poison" quantity="[1,1]" probability="15.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <sound value="rat-squeak-01"/>
        <sound value="rat-squeak-02"/>
        <sound value="rat-squeak-03"/>
      </says>
      <profile name="poisonous" params="5,greater poison"/>
      <profile name="brave"/>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="zombie rat">
    <type class="rodent" subclass="zombierat" tileid="rodent.png:4"/>
    <description>You see a hungry zombie rat and it doesn't like to see you.</description>
    <attributes>
      <atk value="105"/>
      <def value="19"/>
      <hp value="70"/>
      <speed value="0.6"/>
      <size value="1,1"/>
    </attributes>
    <level value="7"/>
    <experience value="70"/>
    <respawn value="1200"/>
    <corpse name="small_animal" harmless="rodent_small"/>
    <drops>
      <item value="cheese" quantity="[2,5]" probability="50.0"/>
      <item value="deadly poison" quantity="[1,1]" probability="8.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="SHREEAK!!"/>
        <noise state="idle follow fight" value="SHAAAAAAA!!"/>
        <sound value="rat-squeak-01"/>
        <sound value="rat-squeak-02"/>
        <sound value="rat-squeak-03"/>
      </says>
      <profile name="poisonous" params="5,deadly poison"/>
      <profile name="brave"/>
      <profile name="animal"/>
      <profile name="offensive"/>
    </ai>
  </creature>

  <creature name="razorrat">
    <type class="rodent" subclass="razorrat" tileid="rodent.png:2"/>
    <description>You see a razorrat, its noise will make you crazy!</description>
    <attributes>
      <atk value="119"/>
      <def value="28"/>
      <hp value="45"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="8"/>
    <experience value="80"/>
    <respawn value="1200"/>
    <corpse name="small_animal" harmless="rodent_small"/>
    <drops>
      <item value="cheese" quantity="[1,3]" probability="50.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <sound value="rat-squeak-01"/>
        <sound value="rat-squeak-02"/>
        <sound value="rat-squeak-03"/>
        <sound value="rat-angry-01"/>
      </says>
      <profile name="brave"/>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="giantrat">
    <type class="rodent" subclass="giantrat" tileid="rodent.png:6"/>
    <description>You see a giant rat. It seems like it survived from an experiment which went wrong.</description>
    <attributes>
      <atk value="173"/>
      <def value="30"/>
      <hp value="110"/>
      <speed value="1.0"/>
      <size value="2,2"/>
    </attributes>
    <level value="15"/>
    <experience value="180"/>
    <respawn value="1230"/>
    <corpse name="animal_2x2" harmless="rodent_large"/>
    <drops>
      <item value="cheese" quantity="[3,7]" probability="80.0"/>
      <item value="rodent trap" quantity="[1,1]" probability="15.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <sound value="rat-angry-02"/>
        <sound value="giantrat-growl-01"/>
        <sound value="giantrat-growl-02"/>
      </says>
      <profile name="brave"/>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="heal" params="5,150"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="beaver">
    <type class="rodent" subclass="beaver" tileid="rodent.png:7"/>
    <description>You see a beaver. It likes to build dams in the river.</description>
    <attributes>
      <atk value="53"/>
      <def value="8"/>
      <hp value="35"/>
      <speed value="0.6"/>
      <size value="1,1"/>
    </attributes>
    <level value="2"/>
    <experience value="20"/>
    <respawn value="900"/>
    <corpse name="animal"/>
    <drops>
      <item value="meat" quantity="[1,2]" probability="80.0"/>
      <item value="wood" quantity="[1,2]" probability="20.0"/>
      <item value="pelt" quantity="[1,1]" probability="100.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

</creatures>
