=== arianne/stendhal/data/conf/creatures.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>


<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                   elementFormDefault="qualified">

	<xsd:element name="creatures" type="Creatures"/>

	<xsd:element name="creature" type="Creature"/>


	<xsd:complexType name="Creatures">
		<xsd:sequence>
			<xsd:element name="creature" type="Creature" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="Creature">
		<xsd:sequence>
			<xsd:element name="type" type="Type" minOccurs="1"/>
			<xsd:element name="hidden" type="xsd:string" minOccurs="0"/>
			<xsd:element name="description" type="xsd:string" minOccurs="0"/>
			<xsd:element name="attributes" type="Attributes" minOccurs="1"/>
			<xsd:element name="level" type="Level" minOccurs="1"/>
			<xsd:element name="experience" type="Experience" minOccurs="1"/>
			<xsd:element name="drops" type="Drops" minOccurs="0"/>
			<xsd:element name="slots" type="Slots" minOccurs="0"/>
			<xsd:element name="equips" type="Equips" minOccurs="0"/>
			<xsd:element name="ai" type="Ai" minOccurs="1"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Item">
		<xsd:attribute name="value" type="xsd:string"/>
		<xsd:attribute name="quantity" type="xsd:string"/>
		<xsd:attribute name="probability" type="xsd:nonNegativeInteger"/>
	</xsd:complexType>

	<xsd:complexType name="Drops">
		<xsd:sequence>
			<xsd:element name="item" type="Item" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Attributes">
		<xsd:sequence>
			<xsd:element name="atk" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="def" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="hp" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="speed" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:decimal"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="size" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="noise" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Ai">
		<xsd:sequence>
			<xsd:element name="says" type="Says" minOccurs="0"/>
			<xsd:element name="profile" type="Profile" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Says">
		<xsd:sequence>
			<xsd:element name="noise" type="Noise" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Noise">
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Profile">
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="params" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Type">
		<xsd:attribute name="class" type="xsd:string"/>
		<xsd:attribute name="subclass" type="xsd:string"/>
		<xsd:attribute name="tileid" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Level">
		<xsd:attribute name="value" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="Experience">
		<xsd:attribute name="value" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="Slots">
		<xsd:sequence>
			<xsd:element name="slot" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Equips">
		<xsd:sequence>
			<xsd:element name="head" type="xsd:string" minOccurs="0"/>
			<xsd:element name="lhand" type="xsd:string" minOccurs="0"/>
			<xsd:element name="rhand" type="xsd:string" minOccurs="0"/>
			<xsd:element name="body" type="xsd:string" minOccurs="0"/>
			<xsd:element name="legs" type="xsd:string" minOccurs="0"/>
			<xsd:element name="feet" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== arianne/stendhal/data/conf/creatures/fairy.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd ">
    
  <creature name="leprechaun">
    <type class="fairy" subclass="leprechaun" tileid="fairy.png:2"/>
    <description>You see a leprechaun, you would be lucky if you found his treasure.</description>
    <attributes>
      <atk value="126"/>
      <def value="20"/>
      <hp value="95"/>
      <speed value="0.6"/>
      <size value="1,1"/>
    </attributes>
    <level value="9"/>
    <experience value="90"/>
    <respawn value="1200"/>
    <corpse name="tiny_humanoid" harmless="leprechaun_green" />
    <drops>
      <item value="money" quantity="[30,100]" probability="30.0"/>
      <item value="sandwich" quantity="[1,1]" probability="2.0"/>
      <item value="lucky charm" quantity="[1,1]" probability="1.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="They're always after my Lucky Charms!!"/>
        <noise state="idle follow fight" value="Clovers and rainbows... stars and horseshoes..."/>
      </says>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
  <creature name="littlefairy">
    <type class="fairy" subclass="littlefairy" tileid="fairy.png:3"/>
    <description>You see a little fairy, which is magical and nice.</description>
    <attributes>
      <atk value="143"/>
      <def value="26"/>
      <hp value="81"/>
      <speed value="0.5"/>
      <size value="1,1"/>
    </attributes>
    <level value="11"/>
    <experience value="120"/>
    <respawn value="1210"/>
    <corpse name="tiny_humanoid"/>
    <drops>
      <item value="money" quantity="[3,7]" probability="90.0"/>
      <item value="fairy cake" quantity="[1,2]" probability="20.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
 
  <creature name="clurichaun">
    <type class="fairy" subclass="clurichaun" tileid="fairy.png:1"/>
    <description>You see a clurichaun. He is rich, but you don't know if you are able to find his gold!</description>
    <attributes>
      <atk value="152"/>
      <def value="27"/>
      <hp value="95"/>
      <speed value="0.4"/>
      <size value="1,1"/>
    </attributes>
    <level value="12"/>
    <experience value="130"/>
    <respawn value="1210"/>
    <corpse name="tiny_humanoid" harmless="leprechaun_purple" />
    <drops>
      <item value="money" quantity="[30,100]" probability="50.0"/>
      <item value="beer" quantity="[2,5]" probability="10.0"/>
      <item value="wine" quantity="[1,5]" probability="10.0"/>
      <item value="lucky charm" quantity="[1,1]" probability="1.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="Join me for a drink, lassie?"/>
        <noise state="idle follow fight" value="Floating blue balloons..."/>
      </says>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature> 
  
  <creature name="baby angel">
    <type class="fairy" subclass="baby_angel" tileid="fairy.png:0"/>
    <description>You see a baby angel. Will it ever get a chance to grow up?</description>
    <attributes>
      <atk value="628"/>
      <def value="100"/>
      <hp value="700"/>
      <speed value="0.9"/>
      <size value="1,1"/>
    </attributes>
    <level value="90"/>
    <experience value="8190"/>
    <respawn value="3530"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[30,60]" probability="100.0"/>
      <item value="fairy cake" quantity="[1,5]" probability="10.0"/>
      <item value="empty scroll" quantity="[1,2]" probability="5.0"/>
      <item value="golden cloak" quantity="[1,1]" probability="2.0"/>
      <item value="liberty helmet" quantity="[1,1]" probability="0.1"/>
      <item value="balloon" quantity="[1,1]" probability="5.0"/>
    </drops>
    <equips>
    </equips>
    <abilities>
      <damage type="light"/>
      <susceptibility type="dark" value="1.3"/>
      <susceptibility type="light" value="0.7"/>
    </abilities>
    <ai>
      <says>
        <noise state="idle follow fight" value="I want to grow to be mighty!"/>
	<sound value="sneeze-baby-1"/>
      </says>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="heal" params="5,50"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
   
</creatures>

=== arianne/stendhal/data/conf/creatures/undead_vampire.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd">

  <creature name="vampire bride">
    <type class="vampire" subclass="vampire_lord_bride" tileid="vampire.png:0"/>
    <description>You see a vampire bride. She was resurrected from the dead by a wicked vampire lord.</description>
    <attributes>
      <atk value="186"/>
      <def value="4"/>
      <hp value="800"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="20"/>
    <experience value="280"/>
    <respawn value="1260"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[10,30]" probability="75.0"/>
      <item value="potion" quantity="[1,2]" probability="30.0"/>
      <item value="greater antidote" quantity="[1,2]" probability="50.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <sound value="vampirette_hiss-01"/>
      </says>
      <profile name="offensive"/>
      <profile name="lifesteal" params="0.5"/>
      <profile name="human"/>
      <profile name="heal" params="5,50"/>
      <profile name="patrolling"/>
      <profile name="strategy" params=",outfit_changer(hand_to_hand;vampire_lord_bride;vampire_lord_bride_evil),"/>
    </ai>
  </creature>

  <creature name="vampirette">
    <type class="vampire" subclass="vampirette" tileid="vampire.png:4"/>
    <description>You see a Vampirette. Beware of its sharp teeth! She wants to drink your blood and turn you into a vampire!</description>
    <attributes>
      <atk value="353"/>
      <def value="43"/>
      <hp value="140"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="40"/>
    <experience value="1040"/>
    <respawn value="1520"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[10,50]" probability="100.0"/>
      <item value="potion" quantity="[1,2]" probability="30.0"/>
      <item value="vampirette entrails" quantity="[1,1]" probability="100.0"/>
      <item value="vampire cloak" quantity="[1,1]" probability="0.05"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <sound value="vampirette_hiss-01"/>
      </says>
      <profile name="offensive"/>
      <profile name="lifesteal" params="0.8"/>
      <profile name="human"/>
      <profile name="heal" params="5,50"/>
      <profile name="patrolling"/>
      <profile name="strategy" params=",outfit_changer(hand_to_hand;vampirette;vampirette_evil),"/>
    </ai>
  </creature>

  <creature name="vampire lord">
    <type class="vampire" subclass="vampire_lord" tileid="vampire.png:2"/>
    <description>You see a vampire lord. Be careful, he is after your blood!</description>
    <attributes>
      <atk value="497"/>
      <def value="35"/>
      <hp value="750"/>
      <speed value="1.0"/>
      <size value="1,1"/>
    </attributes>
    <level value="65"/>
    <experience value="3390"/>
    <respawn value="2000"/>
    <corpse name="humanoid"/>
    <drops>
      <item value="money" quantity="[15,100]" probability="100.0"/>
      <item value="mega potion" quantity="[1,2]" probability="55.0"/>
      <item value="vampire cloak" quantity="[1,1]" probability="1.0"/>
      <item value="vampire sword" quantity="[1,1]" probability="0.1"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <text state="idle follow fight" value="I vant to drink your blood!"/>
        <sound value="laugh-evil-04"/>
      </says>
      <profile name="offensive"/>
      <profile name="lifesteal" params="1"/>
      <profile name="human"/>
      <profile name="heal" params="5,50"/>
      <profile name="strategy" params=",outfit_changer(attack_weakest;vampire_lord;vampire_lord_evil),"/>
    </ai>
  </creature>

</creatures>

=== arianne/stendhal/data/conf/creatures/insect.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd">

  <creature name="killer bee">
    <type class="insect" subclass="killer_bee" tileid="insect.png:0"/>
    <description>You see a killer bee which will sting you to death!</description>
    <attributes>
      <atk value="170"/>
      <ratk value="170"/>
      <def value="25"/>
      <hp value="100"/>
      <speed value="0.6"/>
      <size value="1,1"/>
    </attributes>
    <level value="15"/>
    <experience value="200"/>
    <respawn value="1000"/>
    <corpse name="small_boneless"/>
    <drops>
      <item value="honey" quantity="[1,2]" probability="15.0"/>
      <item value="poison" quantity="[1,1]" probability="15.0"/>
    </drops>
    <equips>
      <slot name="lhand" item="steel arrow" quantity="10000"/>
      <slot name="rhand" item="dummy_ranged" quantity="1"/>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="BbzzZZzzz!"/>
        <sound value="bee-1"/>
      </says>
      <profile name="poisonous" params="10,poison"/>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="archer"/>
      <profile name="patrolling"/>
      <profile name="active_idle"/>
      <profile name="flying"/>
    </ai>
  </creature>

  <creature name="tiny scarab">
    <type class="insect" subclass="scarab_tiny" tileid="insect.png:1"/>
    <description></description>
    <attributes>
      <atk value="182"/>
      <def value="42"/>
      <hp value="180"/>
      <speed value="0.8"/>
      <size value="1,1"/>
    </attributes>
    <level value="23"/>
    <experience value="364"/>
    <respawn value="1290"/>
    <corpse name="carapace" harmless="carapace"/>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

<!-- disabled
  <creature name="scarab">
    <type class="insect" subclass="scarab" tileid="insect.png:2"/>
    <description></description>
    <attributes>
      <atk value="1"/>
      <def value="1"/>
      <hp value="1"/>
      <speed value="0.9"/>
      <size value="1,1"/>
    </attributes>
    <level value="1"/>
    <experience value="1"/>
    <respawn value="1000"/>
    <corpse name="carapace" harmless="carapace"/>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="red scarab">
    <type class="insect" subclass="scarab_red" tileid="insect.png:3"/>
    <description></description>
    <attributes>
      <atk value="1"/>
      <def value="1"/>
      <hp value="1"/>
      <speed value="0.9"/>
      <size value="1,1"/>
    </attributes>
    <level value="1"/>
    <experience value="1"/>
    <respawn value="1000"/>
    <corpse name="carapace" harmless="carapace"/>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
-->

  <creature name="water scarab">
    <type class="insect" subclass="scarab_blue" tileid="insect.png:4"/>
    <description></description>
    <attributes>
      <atk value="358"/>
      <def value="59"/>
      <hp value="1450"/>
      <speed value="0.9"/>
      <size value="1,1"/>
    </attributes>
    <level value="94"/>
    <experience value="9110"/>
    <respawn value="3900"/> <!-- 19.5 minutes -->
    <corpse name="carapace" harmless="carapace"/>
    <drops>
      <item value="placid ring" quantity="[1,1]" probability="0.75"/>
    </drops>
    <ai>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

</creatures>

=== arianne/stendhal/data/conf/creatures/animal_aquatic.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd ">

  <!-- START: cephalopod -->

  <creature name="kraken">
	<type class="huge_animal" subclass="kraken" tileid="huge_animal.png:13"/>
	<description>From the depths of the sea rises a Kraken!</description>
	<attributes>
	<atk value="887"/>
	<def value="114"/>
	<hp value="1935"/>
	<speed value="1"/>
	<size value="3,2"/>
	</attributes>
	<level value="155"/>
	<experience value="38830"/>
    <respawn value="5400"/>
    <corpse name="animal_2x2" harmless="bag_2x2"/>
    <drops>
      <item value="greater potion" quantity="[2,6]" probability="75.0"/>
      <item value="greater poison" quantity="[1,2]" probability="90.0"/>
      <item value="orcish sword" quantity="[1,1]" probability="0.3"/>
      <item value="money" quantity="[30,150]" probability="100.0"/>
    </drops>
    <equips>
    </equips>
    <abilities>
      <susceptibility type="fire" value="0.2"/>
      <susceptibility type="ice" value="1.5"/>
    </abilities>
    <ai>
      <profile name="poisonous" params="15,deadly poison"/>
      <profile name="brave"/>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="heal" params="5,50"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <creature name="neo kraken">
	<type class="huge_animal" subclass="kraken_neo" tileid="huge_animal.png:0"/>
	<description></description>
	<attributes>
	  <atk value="992"/>
	  <def value="122"/>
	  <hp value="3000"/>
	  <speed value="1"/>
	  <size value="3,2"/>
	</attributes>
	<level value="180"/>
	<experience value="57400"/>
    <respawn value="18600"/> <!-- 93 minutes -->
    <corpse name="animal_2x2" harmless="bag_2x2"/>
    <drops>
      <item value="money" quantity="[50,100]" probability="33.0"/>
      <item value="mega potion" quantity="[1,2]" probability="2.0"/>
      <item value="disease poison" quantity="[1,2]" probability="15.0"/>
      <item value="magic plate legs" quantity="[1,1]" probability="0.75"/>
    </drops>
    <equips>
    </equips>
    <abilities>
      <susceptibility type="fire" value="0.2"/>
      <susceptibility type="ice" value="1.5"/>
    </abilities>
    <ai>
      <profile name="poisonous" params="15,deadly poison"/>
      <profile name="brave"/>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="heal" params="5,50"/>
      <profile name="patrolling"/>
    </ai>
  </creature>

  <!-- END: cephalopod -->

  <!-- START: fish -->

  <creature name="shark">
    <type class="giant_animal" subclass="shark" tileid="giant_animal.png:2"/>
    <description>A shark! Best move cautiously.</description>
    <attributes>
      <atk value="340"/>
      <def value="50"/>
      <hp value="180"/>
      <speed value="0.5"/>
      <size value="2,2"/>
    </attributes>
    <level value="39"/>
    <experience value="1500" />
    <respawn value="1230"/>
    <corpse name="shark_2x2" harmless="shark_2x2" width="2" height="2" />
    <drops>
      <item value="money" quantity="[7,40]" probability="30.0"/>
      <item value="char" quantity="[2,6]" probability="15.0"/>
      <item value="cod" quantity="[1,5]" probability="70.0"/>
      <item value="clownfish" quantity="[1,3]" probability="50.0"/>
    </drops>
    <equips>
    </equips>
    <abilities>
      <susceptibility type="fire" value="0.2"/>
      <susceptibility type="ice" value="2.0"/>
    </abilities>
    <ai>
      <says>
      </says>
      <profile name="brave"/>
      <profile name="animal"/>
      <profile name="offensive"/>
      <profile name="heal" params="5,150"/>
      <profile name="patrolling"/>
   </ai>
 </creature>

  <!-- END: fish -->

</creatures>

=== arianne/stendhal/data/conf/creatures/gnome.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../creatures.xsd ">
  
  <!-- START: gnome -->
  
  <creature name="gnome">
    <type class="gnome" subclass="gnome" tileid="gnome.png:0"/>
    <description>You see a gnome who lives in the mountains.</description>
    <attributes>
      <atk value="51"/>
      <def value="7"/>
      <hp value="50"/>
      <speed value="0.5"/>
      <size value="1,1"/>
    </attributes>
    <level value="2"/>
    <experience value="20"/>
    <respawn value="900"/>
    <corpse name="tiny_humanoid" harmless="gnome" />
    <drops>
      <item value="money" quantity="[2,5]" probability="70.0"/>
      <item value="minor potion" quantity="[1,1]" probability="5.0"/>
      <item value="button mushroom" quantity="[3,6]" probability="10.0"/>
      <item value="leather armor" quantity="[1,1]" probability="10.0"/>
      <item value="buckler" quantity="[1,1]" probability="5.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="Giiiiiaaants! Run away!"/>
      </says>
      <profile name="offensive"/>
      <profile name="coward"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
  <creature name="mage gnome">
    <type class="gnome" subclass="woman_gnome" tileid="gnome.png:1"/>
    <description>You see a mage gnome, she cleans the dirty mountain.</description>
    <attributes>
      <atk value="52"/>
      <def value="7"/>
      <hp value="50"/>
      <speed value="0.5"/>
      <size value="1,1"/>
    </attributes>
    <level value="2"/>
    <experience value="20"/>
    <respawn value="900"/>
    <corpse name="tiny_humanoid" harmless="gnome" />
    <drops>
      <item value="money" quantity="[2,5]" probability="70.0"/>
      <item value="antidote" quantity="[1,1]" probability="10.0"/>
      <item value="porcini" quantity="[1,10]" probability="10.0"/>
      <item value="leather armor" quantity="[1,1]" probability="10.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="Giiiiiaaants! Run away!"/>
      </says>
      <profile name="offensive"/>
      <profile name="coward"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
  <!-- END: gnome -->
  
  <!-- START: militant -->
  
  <creature name="infantry gnome">
    <type class="gnome" subclass="infantryman" tileid="gnome_patrol.png:0"/>
    <description>You see an infantry gnome who will protect his little town against the humans!</description>
    <attributes>
      <atk value="58"/>
      <def value="15"/>
      <hp value="60"/>
      <speed value="0.5"/>
      <size value="1,1"/>
    </attributes>
    <level value="5"/>
    <experience value="50"/>
    <respawn value="1200"/>
    <corpse name="tiny_humanoid" harmless="gnome_military" />
    <drops>
      <item value="money" quantity="[4,10]" probability="70.0"/>
      <item value="carrot" quantity="[2,10]" probability="20.0"/>
      <item value="porcini" quantity="[1,10]" probability="10.0"/>
      <item value="potion" quantity="[1,1]" probability="20.0"/>
    </drops>
    <equips>
          <slot name="rhand" item="dagger"/>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="Ready! Aim! Runnnnnnnnnnn"/>
      </says>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
  <creature name="cavalryman gnome">
    <type class="gnome" subclass="cavalryman" tileid="gnome_patrol.png:1"/>
    <description>You see a cavalryman gnome who does long travels to search for gold.</description>
    <attributes>
      <atk value="90"/>
      <def value="14"/>
      <hp value="65"/>
      <speed value="0.5"/>
      <size value="1,1"/>
    </attributes>
    <level value="5"/>
    <experience value="55"/>
    <respawn value="1200"/>
    <corpse name="tiny_humanoid" harmless="gnome_military" />
    <drops>
      <item value="money" quantity="[6,14]" probability="70.0"/>
      <item value="chain boots" quantity="[1,1]" probability="15.0"/>
      <item value="robins hat" quantity="[1,1]" probability="20.0"/>
      <item value="potion" quantity="[1,1]" probability="20.0"/>
    </drops>
    <equips>
    </equips>
    <ai>
      <says>
        <noise state="idle follow fight" value="Ready! Aim! Runnnnnnnnnnn"/>
        <sound value="pig-3" />
      </says>
      <profile name="brave"/>
      <profile name="offensive"/>
      <profile name="human"/>
      <profile name="patrolling"/>
    </ai>
  </creature>
  
  <!-- END: militant -->
  
</creatures>
