=== arianne/stendhal/data/conf/groups.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
    xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
    xmlns:Q3="stendhal">

  <element name="groups" type="Q3:groupsType"/>

  <complexType name="groupsType">
    <sequence>
      <element name="group" type="Q3:groupType" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <complexType name="groupType">
    <attribute name="uri" type="anyURI"/>
  </complexType>

</schema>

=== arianne/stendhal/data/conf/creatures.xml
<?xml version="1.0" encoding="UTF-8"?>
<groups xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal groups.xsd ">
	<group uri="creatures/angel.xml" />
	<group uri="creatures/animal.xml" />
	<group uri="creatures/animal_aquatic.xml" />
	<group uri="creatures/animal_fowl.xml" />
	<group uri="creatures/beast.xml" />
	<group uri="creatures/chess.xml" />
    <group uri="creatures/demon.xml" />
    <group uri="creatures/dragon.xml" />
	<group uri="creatures/dwarf.xml" />
	<group uri="creatures/elemental.xml" />
	<group uri="creatures/elf.xml" />
	<group uri="creatures/giant.xml" />
    <group uri="creatures/gnome.xml" />
	<group uri="creatures/goblin.xml" />
	<group uri="creatures/golem.xml" />
	<group uri="creatures/human.xml" />
	<group uri="creatures/human_assassin.xml" />
	<group uri="creatures/human_amazon.xml" />
	<group uri="creatures/human_barbarian.xml" />
	<group uri="creatures/human_blordrough.xml" />
	<group uri="creatures/human_cannibal.xml" />
	<group uri="creatures/human_chaos.xml" />
	<group uri="creatures/human_imperial.xml" />
	<group uri="creatures/human_madaram.xml" />
	<group uri="creatures/human_mithrilbourgh.xml" />
	<group uri="creatures/human_risecia.xml" />
	<group uri="creatures/humanoid.xml" />
	<group uri="creatures/hybrid.xml" />
	<group uri="creatures/insect.xml" />
	<group uri="creatures/kobold.xml" />
	<group uri="creatures/mutant.xml" />
	<group uri="creatures/mythical_being.xml" />
	<group uri="creatures/northpole.xml" />
	<group uri="creatures/ogre.xml" />
    <group uri="creatures/oni.xml" />
    <group uri="creatures/orc.xml" />
    <group uri="creatures/reptile.xml" />
    <group uri="creatures/rodent.xml" />
    <group uri="creatures/slime.xml" />
    <group uri="creatures/spider.xml" />
	<group uri="creatures/troll.xml" />
	<group uri="creatures/undead.xml" />
	<group uri="creatures/undead_lich.xml" />
	<group uri="creatures/undead_mummy.xml" />
	<group uri="creatures/undead_skeleton.xml" />
	<group uri="creatures/undead_specter.xml" />
	<group uri="creatures/undead_vampire.xml" />
	<group uri="creatures/undead_zombie.xml" />
</groups>
