=== arianne/stendhal/data/conf/items.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
	xmlns:Q1="stendhal">

	<element name="items" type="Q1:itemGroup"></element>

	<complexType name="itemGroup">
		<sequence>
			<element name="item" type="Q1:itemType" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="itemType">
		<sequence>
			<element name="type" type="Q1:typeType" />
			<element name="description" type="string"></element>
			<element name="implementation" type="Q1:implementation"></element>
			<element name="behavior" type="Q1:behavior" minOccurs="0" maxOccurs="1"></element>
			<element name="attributes" type="Q1:attributes"></element>
			<element name="weight" type="Q1:attribute"></element>
			<element name="value" type="Q1:attribute"></element>
			<element name="preview" type="string" minOccurs="0" maxOccurs="1" />
			<element name="damage" type="Q1:damage" minOccurs="0"></element>
			<element name="susceptibility" type="Q1:susceptibility" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="equipable" type="Q1:equipable"></element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>

	<complexType name="typeType">
		<attribute name="class" type="string"></attribute>
		<attribute name="subclass" type="string"></attribute>
		<attribute name="tileid" type="int"></attribute>
	</complexType>

	<complexType name="implementation">
		<attribute name="class-name" type="string"></attribute>
	</complexType>

	<complexType name="behavior">
		<sequence>
			<element name="parameter" type="Q1:pair" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="class-name" type="string"/>
	</complexType>

	<complexType name="pair">
		<attribute name="name" type="string"/>
		<attribute name="value" type="string"/>
	</complexType>

	<complexType name="attributes">
		<sequence>
			<element name="infostring" type="Q1:attribute" minOccurs="0"/>
			<element name="atk" type="Q1:attribute" minOccurs="0"/>
			<element name="def" type="Q1:attribute" minOccurs="0"/>
			<element name="ratk" type="Q1:attribute" minOccurs="0"/>
			<element name="immunization" type="Q1:attribute" minOccurs="0"/>
			<element name="amount" type="Q1:attribute" minOccurs="0"/>
			<element name="frequency" type="Q1:attribute" minOccurs="0"/>
			<element name="range" type="Q1:attribute" minOccurs="0"/>
			<element name="quantity" type="Q1:attribute" minOccurs="0"/>
			<element name="max_quantity" type="Q1:attribute" minOccurs="0"/>
			<element name="regen" type="Q1:attribute" minOccurs="0"/>
			<element name="rate" type="Q1:attribute" minOccurs="0"/>
			<element name="lifesteal" type="Q1:attribute" minOccurs="0"/>
			<element name="persistent" type="Q1:attribute" minOccurs="0"/>
			<element name="min_level" type="Q1:attribute" minOccurs="0"/>
			<element name="life_support" type="Q1:attribute" minOccurs="0"/>
			<element name="slot_name" type="Q1:attribute" minOccurs="0"/>
			<element name="undroppableondeath" type="Q1:attribute" minOccurs="0"/>
			<element name="autobind" type="Q1:attribute" minOccurs="0"/>
			<element name="slot_size" type="Q1:attribute" minOccurs="0"/>
			<element name="menu" type="Q1:attribute" minOccurs="0"/>
			<element name="durability" type="Q1:attribute" minOccurs="0" maxOccurs="1"/>
			<element name="status_resist" type="Q1:stresist" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="attribute">
		<attribute name="value" type="string"></attribute>
	</complexType>

	<complexType name="equipable">
		<sequence>
			<element name="slot" type="Q1:slot" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="slot">
		<attribute name="name" type="string"></attribute>
	</complexType>

	<complexType name="damage">
		<attribute name="type" type="string" />
	</complexType>

	<complexType name="susceptibility">
		<attribute name="type" type="string" />
		<attribute name="value" type="decimal" />
	</complexType>

	<complexType name="stresist">
		<attribute name="type" type="string" />
		<attribute name="value" type="decimal" />
		<attribute name="slots" type="string" />
	</complexType>

</schema>

=== arianne/stendhal/data/conf/items/relics.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../items.xsd">

  <item name="skull ring">
    <type class="relic" subclass="skull_ring" tileid="-1"/>
    <description>You see a skull ring.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
    </attributes>
    <weight value="1.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="finger"/>
      <slot name="keyring"/>
    </equipable>
  </item>

  <item name="amulet">
    <type class="relic" subclass="amulet" tileid="-1"/>
    <description/>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
    </attributes>
    <weight value="1.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="keyring"/>
    </equipable>
  </item>

<!-- disabled
  <item name="ankh" condition="stendhal.testserver">
    <type class="relic" subclass="ankh" tileid="-1"/>
    <description>You see a mysterious ankh. You don't know what it is for.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
    </attributes>
    <weight value="1.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="keyring"/>
    </equipable>
  </item>
-->

</items>

=== arianne/stendhal/data/conf/items/containers.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">
  <item name="flask">
    <type class="container" subclass="bottle" tileid="-1"/>
    <description>You see a flask. This flask is good for storing medicine.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>    <attributes>
      <quantity value="1"/>
    </attributes>
    <weight value="1.0"/>
    <value value="1"/>
    <equipable>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="bottle">
    <type class="container" subclass="bottle" tileid="-1"/>
    <description>You see a bottle. It is empty, someone drank the contents</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>    <attributes>
      <quantity value="1"/>
    </attributes>
    <weight value="1.0"/>
    <value value="1"/>
    <equipable>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="big bottle">
    <type class="container" subclass="big_bottle" tileid="-1"/>
    <description>You see a big bottle.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>    <attributes>
      <quantity value="1"/>
    </attributes>
    <weight value="1.0"/>
    <value value="1"/>
    <equipable>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="empty goblet">
    <type class="container" subclass="empty_goblet" tileid="-1"/>
    <description>You see an empty goblet.  You wonder what could it hold.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
    </attributes>
    <weight value="1.0"/>
    <value value="1"/>
    <equipable>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="goblet">
    <type class="container" subclass="full_goblet" tileid="-1"/>
    <description>You see a goblet.  You look at its contents, and shiver at the blood inside.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>    <attributes>
      <quantity value="1"/>
    </attributes>
    <weight value="1.0"/>
    <value value="1"/>
    <equipable>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>
</items>

=== arianne/stendhal/data/conf/items/boxes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../items.xsd">

  <item name="present">
    <type class="box" subclass="present" tileid="-1"/>
    <description>You see a present. Open it.</description>
    <implementation class-name="games.stendhal.server.entity.item.Present"/>
    <attributes>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="basket">
    <type class="box" subclass="basket" tileid="-1"/>
    <description>You see an easter basket. Look inside.</description>
    <implementation class-name="games.stendhal.server.entity.item.Basket"/>
    <attributes>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="stocking">
    <type class="box" subclass="stocking" tileid="-1"/>
    <description>You see a christmas stocking. Look inside.</description>
    <implementation class-name="games.stendhal.server.entity.item.Stocking"/>
    <attributes>
    </attributes>
    <weight value="0.01"/>
    <value value="100"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

</items>

=== arianne/stendhal/data/conf/items/herbs.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">
  <item name="arandula">
    <type class="herb" subclass="arandula" tileid="-1"/>
    <description>You see a arandula. It has medicinal properties, if the right person uses it.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>    <attributes>
      <quantity value="1"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="kokuda">
    <type class="herb" subclass="kokuda" tileid="-1"/>
    <description>You see a kokuda. It has medicinal properties, if the right person uses it.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>    <attributes>
      <quantity value="1"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="kekik">
    <type class="herb" subclass="kekik" tileid="-1"/>
    <description>You see a kekik. It is a herb which can have healing properties.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>    <attributes>
      <quantity value="1"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="mandragora">
    <type class="herb" subclass="mandragora" tileid="-1"/>
    <description>You see a root of mandragora. It has medicinal properties, if the right person uses it.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>    <attributes>
      <quantity value="1"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="sclaria">
    <type class="herb" subclass="sclaria" tileid="-1"/>
    <description>You see the herb sclaria. The smell is calming.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>    <attributes>
      <quantity value="1"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

</items>

=== arianne/stendhal/data/conf/items/furniture.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="stendhal ../items.xsd">

	<item name="picture in wooden frame">
		<type class="furniture" subclass="picture_in_wooden_frame"/>
		<description>You see a picture in a wooden frame</description>
		<implementation class-name="games.stendhal.server.entity.item.ExaminableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>
</items>

=== arianne/stendhal/data/conf/items/crystals.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../items.xsd">

  <item name="red emotion crystal">
    <type class="crystal" subclass="crystal_red" tileid="-1"/>
    <description>You see a red emotion crystal. It feels hot to the touch.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.1"/>
    <value value="100"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="purple emotion crystal">
    <type class="crystal" subclass="crystal_purple" tileid="-1"/>
    <description>You see a purple emotion crystal. It feels cold to the touch.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.1"/>
    <value value="100"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="yellow emotion crystal">
    <type class="crystal" subclass="crystal_yellow" tileid="-1"/>
    <description>You see a yellow emotion crystal. It energizes you.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.1"/>
    <value value="100"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="pink emotion crystal">
    <type class="crystal" subclass="crystal_pink" tileid="-1"/>
    <description>You see a pink emotion crystal. It almost feels soft.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.1"/>
    <value value="100"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="blue emotion crystal">
    <type class="crystal" subclass="crystal_blue" tileid="-1"/>
    <description>You see a blue emotion crystal. While holding it your worries seem to disappear.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.1"/>
    <value value="100"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

</items>
