=== arianne/stendhal/data/conf/items.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
	xmlns:Q1="stendhal">

	<element name="items" type="Q1:itemGroup"></element>

	<complexType name="itemGroup">
		<sequence>
			<element name="item" type="Q1:itemType" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="itemType">
		<sequence>
			<element name="type" type="Q1:typeType" />
			<element name="description" type="string"></element>
			<element name="implementation" type="Q1:implementation"></element>
			<element name="behavior" type="Q1:behavior" minOccurs="0" maxOccurs="1"></element>
			<element name="attributes" type="Q1:attributes"></element>
			<element name="weight" type="Q1:attribute"></element>
			<element name="value" type="Q1:attribute"></element>
			<element name="preview" type="string" minOccurs="0" maxOccurs="1" />
			<element name="damage" type="Q1:damage" minOccurs="0"></element>
			<element name="susceptibility" type="Q1:susceptibility" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="equipable" type="Q1:equipable"></element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>

	<complexType name="typeType">
		<attribute name="class" type="string"></attribute>
		<attribute name="subclass" type="string"></attribute>
		<attribute name="tileid" type="int"></attribute>
	</complexType>

	<complexType name="implementation">
		<attribute name="class-name" type="string"></attribute>
	</complexType>

	<complexType name="behavior">
		<sequence>
			<element name="parameter" type="Q1:pair" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="class-name" type="string"/>
	</complexType>

	<complexType name="pair">
		<attribute name="name" type="string"/>
		<attribute name="value" type="string"/>
	</complexType>

	<complexType name="attributes">
		<sequence>
			<element name="infostring" type="Q1:attribute" minOccurs="0"/>
			<element name="atk" type="Q1:attribute" minOccurs="0"/>
			<element name="def" type="Q1:attribute" minOccurs="0"/>
			<element name="ratk" type="Q1:attribute" minOccurs="0"/>
			<element name="immunization" type="Q1:attribute" minOccurs="0"/>
			<element name="amount" type="Q1:attribute" minOccurs="0"/>
			<element name="frequency" type="Q1:attribute" minOccurs="0"/>
			<element name="range" type="Q1:attribute" minOccurs="0"/>
			<element name="quantity" type="Q1:attribute" minOccurs="0"/>
			<element name="max_quantity" type="Q1:attribute" minOccurs="0"/>
			<element name="regen" type="Q1:attribute" minOccurs="0"/>
			<element name="rate" type="Q1:attribute" minOccurs="0"/>
			<element name="lifesteal" type="Q1:attribute" minOccurs="0"/>
			<element name="persistent" type="Q1:attribute" minOccurs="0"/>
			<element name="min_level" type="Q1:attribute" minOccurs="0"/>
			<element name="life_support" type="Q1:attribute" minOccurs="0"/>
			<element name="slot_name" type="Q1:attribute" minOccurs="0"/>
			<element name="undroppableondeath" type="Q1:attribute" minOccurs="0"/>
			<element name="autobind" type="Q1:attribute" minOccurs="0"/>
			<element name="slot_size" type="Q1:attribute" minOccurs="0"/>
			<element name="menu" type="Q1:attribute" minOccurs="0"/>
			<element name="durability" type="Q1:attribute" minOccurs="0" maxOccurs="1"/>
			<element name="status_resist" type="Q1:stresist" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="attribute">
		<attribute name="value" type="string"></attribute>
	</complexType>

	<complexType name="equipable">
		<sequence>
			<element name="slot" type="Q1:slot" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="slot">
		<attribute name="name" type="string"></attribute>
	</complexType>

	<complexType name="damage">
		<attribute name="type" type="string" />
	</complexType>

	<complexType name="susceptibility">
		<attribute name="type" type="string" />
		<attribute name="value" type="decimal" />
	</complexType>

	<complexType name="stresist">
		<attribute name="type" type="string" />
		<attribute name="value" type="decimal" />
		<attribute name="slots" type="string" />
	</complexType>

</schema>

=== arianne/stendhal/data/conf/items/helmets.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">
  <item name="leather helmet">
    <type class="helmet" subclass="leather_helmet" tileid="-1"/>
    <description>You see a leather helmet, it seems more like a hat than a defensive item.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="1"/>
    </attributes>
    <weight value="2.0"/>
    <value value="7"/>
    <equipable>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="trophy helmet">
    <type class="helmet" subclass="golden_horned_barbute" tileid="-1"/>
    <description/>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="1"/>
    </attributes>
    <weight value="10.0"/>
    <value value="7"/>
    <equipable>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="robins hat">
    <type class="helmet" subclass="robins_hat" tileid="-1"/>
    <description>You see a robins hat. It's cute but that's about it.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="2"/>
    </attributes>
    <weight value="6.0"/>
    <value value="56"/>
    <equipable>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="studded helmet">
    <type class="helmet" subclass="studded_helmet" tileid="-1"/>
    <description>You see a studded helmet, it should protect your head against cuts but perhaps not hard blows.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="2"/>
    </attributes>
    <weight value="3.0"/>
    <value value="56"/>
    <equipable>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="chain helmet">
    <type class="helmet" subclass="chain_helmet" tileid="-1"/>
    <description>You see a solid chain helmet, it will be excellent protection for your head.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="4"/>
    </attributes>
    <weight value="6.0"/>
    <value value="448"/>
    <equipable>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="viking helmet">
    <type class="helmet" subclass="horned_helmet" tileid="-1"/>
    <description>You see a viking helmet. The previous owner wore it to many battles.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="5"/>
    </attributes>
    <weight value="6.0"/>
    <value value="875"/>
    <equipable>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="aventail">
    <type class="helmet" subclass="aventail" tileid="-1"/>
    <description>You see a aventail. It's a clever design.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="6"/>
    </attributes>
    <weight value="6.0"/>
    <value value="1512"/>
    <equipable>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="red helmet">
    <type class="helmet" subclass="red_helmet" tileid="-1"/>
    <description>You see a red helmet, it reminds you of a jester's hat but you can be sure it has better protection than that.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="7"/>
    </attributes>
    <weight value="6.0"/>
    <value value="1512"/>
    <equipable>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="blue helmet">
    <type class="helmet" subclass="blue_helmet" tileid="-1"/>
    <description>You see a brand new blue helmet.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="7"/>
    </attributes>
    <weight value="8.0"/>
    <value value="3012"/>
    <equipable>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="golden helmet">
    <type class="helmet" subclass="golden_helmet" tileid="-1"/>
    <description>You see a heavy golden helmet. The thick metal should protect you against almost anything.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="9"/>
    </attributes>
    <weight value="15.0"/>
    <value value="5103"/>
    <equipable>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="shadow helmet">
    <type class="helmet" subclass="shadow_helmet" tileid="-1"/>
    <description>You see a heavy shadow helmet. Instead of shining, it darkly gleams.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="10"/>
    </attributes>
    <weight value="15.0"/>
    <value value="7000"/>
    <susceptibility type="light" value="1.4"/>
    <susceptibility type="dark" value="0.85"/> 
    <equipable>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="horned golden helmet">
    <type class="helmet" subclass="enhanced_golden_helmet" tileid="-1"/>
    <description>You see a horned golden helmet.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="12"/>
    </attributes>
    <weight value="15.0"/>
    <value value="12096"/>
    <equipable>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="chaos helmet">
    <type class="helmet" subclass="chaos_helmet" tileid="-1"/>
    <description>You see a chaos helmet.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="14"/>
    </attributes>
    <weight value="15.0"/>
    <value value="19208"/>
    <equipable>
      <slot name="bag"/>
      <slot name="head"/>
    </equipable>
  </item>

  <item name="mainio helmet">
    <type class="helmet" subclass="lion_clan_helmet" tileid="-1"/>
    <description>You see a strange mainio helmet. You can barely see when wearing it, but it protects your head very well.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="16"/>
    </attributes>
    <weight value="15.0"/>
    <value value="39208"/>
    <equipable>
      <slot name="bag"/>
      <slot name="head"/>
    </equipable>
  </item>

  <item name="magic chain helmet">
    <type class="helmet" subclass="magic_chain_helmet" tileid="-1"/>
    <description>You see a magic chain helmet.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="22"/>
    </attributes>
    <weight value="15.0"/>
    <value value="74536"/>
    <susceptibility type="fire" value="0.98"/>
    <susceptibility type="ice" value="0.98"/>
    <susceptibility type="dark" value="0.98"/>
    <susceptibility type="light" value="0.98"/>
    <equipable>
      <slot name="head"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="liberty helmet">
    <type class="helmet" subclass="liberty_helmet" tileid="-1"/>
    <description>You see the liberty helmet. It's light and strong, you feel free wearing it.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="24"/>
    </attributes>
    <weight value="5.0"/>
    <value value="100208"/>
    <equipable>
      <slot name="bag"/>
      <slot name="head"/>
    </equipable>
  </item>

  <item name="black helmet">
    <type class="helmet" subclass="black_helmet" tileid="-1"/>
    <description>You see a black helmet.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="26"/>
    </attributes>
    <weight value="15.0"/>
    <value value="123032"/>
    <susceptibility type="light" value="1.3"/>
    <susceptibility type="dark" value="0.85"/> 
    <equipable>
      <slot name="bag"/>
      <slot name="head"/>
    </equipable>
  </item>
 
  <item name="mithril helmet">
    <type class="helmet" subclass="mithril_helmet" tileid="-1"/>
    <description>You see a mithril helmet.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="29"/>
    </attributes>
    <weight value="12.0"/>
    <value value="323032"/>
    <susceptibility type="light" value="0.9"/>
    <susceptibility type="dark" value="1.3"/> 
    <equipable>
      <slot name="bag"/>
      <slot name="head"/>
    </equipable>
  </item>
</items>

=== arianne/stendhal/data/conf/items/missiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">

  <item name="snowball">
    <type class="missile" subclass="snowballs" tileid="-1"/>
    <description>You see snowballs. You can throw them at your friends or put it in your bag to keep your fish fresh. But be careful, there could be little stones in it.</description>
    <implementation class-name="games.stendhal.server.entity.item.NoStatsStackableItem"/>
    <attributes>
      <ratk value="-1"/>
      <range value="8"/>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.1"/>
    <value value="80"/>
    <damage type="ice"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="vomit">
    <type class="missile" subclass="vomit" tileid="-1"/>
    <description>You see a pile of vomit. Gross!</description>
    <implementation class-name="games.stendhal.server.entity.item.NoStatsStackableItem"/>
    <attributes>
      <ratk value="-1"/>
      <range value="5"/>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.1"/>
    <value value="2"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <!--<item name="dart">
    <type class="missile" subclass="dart" tileid="-1"/>
    <description>You see a dart. You'll need to be close before you can use it as a missile. Stand square on, not diagonally, for the best results.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
      <ratk value="2"/>
      <range value="2"/>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.1"/>
    <value value="80"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="power dart">
    <type class="missile" subclass="dart" tileid="-1"/>
    <description>You see a power dart. You'll need to be close before you can use it as a missile. Stand square on, not diagonally, for the best results.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
      <ratk value="4"/>
      <range value="2"/>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.1"/>
    <value value="640"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>-->

  <item name="shuriken">
    <type class="missile" subclass="shuriken" tileid="-1"/>
    <description>You see a shuriken. You'll need to be close before you can use it as a missile. Stand square on, not diagonally, for the best results.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
      <ratk value="6"/>
      <range value="3"/>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.1"/>
    <value value="2160"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="fire shuriken">
    <type class="missile" subclass="fire_shuriken" tileid="-1"/>
    <description>You see a fire shuriken. Throwing this flaming missile unleashes fiendish power.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
      <ratk value="12"/>
      <range value="3"/>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.1"/>
    <value value="2160"/>
    <damage type="fire"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="wooden spear">
    <type class="missile" subclass="wooden_spear" tileid="-1"/>
    <description>You see a wooden spear. You can attack at a distance with this primitive weapon. Stand square on, not diagonally, for the best results.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
      <ratk value="10"/>
      <range value="4"/>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.1"/>
    <value value="10000"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

</items>

=== arianne/stendhal/data/conf/items/special.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">
  <item name="lucky charm">
    <type class="special" subclass="lucky_charm" tileid="-1"/>
    <description>You see a lucky charm. Some believe that it helps their karma in some way, but others think that is superstition.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
      <autobind value=""/>
    </attributes>
    <weight value="1.0"/>
    <value value="100000"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="keyring"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>


   <item name="mithril clasp">
    <type class="special" subclass="mithril_clasp" tileid="-1"/>
    <description>You see a clasp made from mithril, it would provide the fastening for a cloak.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
    </attributes>
    <weight value="1.0"/>
    <value value="200000"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="mythical egg">
    <type class="special" subclass="mythical_egg" tileid="-1"/>
    <description>You see a mythical egg, but you do not know, what it is for.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="1.0"/>
    <value value="100000"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>


  <item name="magical eggshells">
    <type class="special" subclass="eggshells" tileid="-1"/>
    <description>You see shards from a mythical egg. They have magical properties.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1000"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="golden gm token">
    <type class="special" subclass="GM_tokend_gold2" tileid="-1"/>
    <description/>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="silvery gm token">
    <type class="special" subclass="GM_tokend_silver" tileid="-1"/>
    <description/>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="bronze gm token">
    <type class="special" subclass="GM_tokend_bronze" tileid="-1"/>
    <description/>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>
  
  <item name="crystal of anger">
    <type class="special" subclass="crystal_red" tileid="-1" />
    <description>You see a #crystal #of #anger.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item" />
    <attributes>
      <quantity value="1" />
      <max_quantity value="2147483647" />
    </attributes>
    <weight value="0.1" />
    <value value="100" />
    <equipable>
      <slot name="ground" />
      <slot name="content" />
      <slot name="lhand" />
      <slot name="rhand" />
      <slot name="head" />
      <slot name="bag" />
    </equipable>
  </item>
  
  <item name="crystal of fear">
    <type class="special" subclass="crystal_purple" tileid="-1" />
    <description>You see a #crystal #of #fear.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item" />
    <attributes>
      <quantity value="1" />
      <max_quantity value="2147483647" />
    </attributes>
    <weight value="0.1" />
    <value value="100" />
    <equipable>
      <slot name="ground" />
      <slot name="content" />
      <slot name="lhand" />
      <slot name="rhand" />
      <slot name="head" />
      <slot name="bag" />
    </equipable>
  </item>
  
  <item name="crystal of joy">
    <type class="special" subclass="crystal_yellow" tileid="-1" />
    <description>You see a #crystal #of #joy.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item" />
    <attributes>
      <quantity value="1" />
      <max_quantity value="2147483647" />
    </attributes>
    <weight value="0.1" />
    <value value="100" />
    <equipable>
      <slot name="ground" />
      <slot name="content" />
      <slot name="lhand" />
      <slot name="rhand" />
      <slot name="head" />
      <slot name="bag" />
    </equipable>
  </item>
  
  <item name="crystal of love">
    <type class="special" subclass="crystal_pink" tileid="-1" />
    <description>You see a #crystal #of #love.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item" />
    <attributes>
      <quantity value="1" />
      <max_quantity value="2147483647" />
    </attributes>
    <weight value="0.1" />
    <value value="100" />
    <equipable>
      <slot name="ground" />
      <slot name="content" />
      <slot name="lhand" />
      <slot name="rhand" />
      <slot name="head" />
      <slot name="bag" />
    </equipable>
  </item>
  
  <item name="crystal of peace">
    <type class="special" subclass="crystal_blue" tileid="-1" />
    <description>You see a #crystal #of #love.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item" />
    <attributes>
      <quantity value="1" />
      <max_quantity value="2147483647" />
    </attributes>
    <weight value="0.1" />
    <value value="100" />
    <equipable>
      <slot name="ground" />
      <slot name="content" />
      <slot name="lhand" />
      <slot name="rhand" />
      <slot name="head" />
      <slot name="bag" />
    </equipable>
  </item>
  
</items>
