=== arianne/stendhal/data/conf/items.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
	xmlns:Q1="stendhal">

	<element name="items" type="Q1:itemGroup"></element>

	<complexType name="itemGroup">
		<sequence>
			<element name="item" type="Q1:itemType" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="itemType">
		<sequence>
			<element name="type" type="Q1:typeType" />
			<element name="description" type="string"></element>
			<element name="implementation" type="Q1:implementation"></element>
			<element name="behavior" type="Q1:behavior" minOccurs="0" maxOccurs="1"></element>
			<element name="attributes" type="Q1:attributes"></element>
			<element name="weight" type="Q1:attribute"></element>
			<element name="value" type="Q1:attribute"></element>
			<element name="preview" type="string" minOccurs="0" maxOccurs="1" />
			<element name="damage" type="Q1:damage" minOccurs="0"></element>
			<element name="susceptibility" type="Q1:susceptibility" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="equipable" type="Q1:equipable"></element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>

	<complexType name="typeType">
		<attribute name="class" type="string"></attribute>
		<attribute name="subclass" type="string"></attribute>
		<attribute name="tileid" type="int"></attribute>
	</complexType>

	<complexType name="implementation">
		<attribute name="class-name" type="string"></attribute>
	</complexType>

	<complexType name="behavior">
		<sequence>
			<element name="parameter" type="Q1:pair" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="class-name" type="string"/>
	</complexType>

	<complexType name="pair">
		<attribute name="name" type="string"/>
		<attribute name="value" type="string"/>
	</complexType>

	<complexType name="attributes">
		<sequence>
			<element name="infostring" type="Q1:attribute" minOccurs="0"/>
			<element name="atk" type="Q1:attribute" minOccurs="0"/>
			<element name="def" type="Q1:attribute" minOccurs="0"/>
			<element name="ratk" type="Q1:attribute" minOccurs="0"/>
			<element name="immunization" type="Q1:attribute" minOccurs="0"/>
			<element name="amount" type="Q1:attribute" minOccurs="0"/>
			<element name="frequency" type="Q1:attribute" minOccurs="0"/>
			<element name="range" type="Q1:attribute" minOccurs="0"/>
			<element name="quantity" type="Q1:attribute" minOccurs="0"/>
			<element name="max_quantity" type="Q1:attribute" minOccurs="0"/>
			<element name="regen" type="Q1:attribute" minOccurs="0"/>
			<element name="rate" type="Q1:attribute" minOccurs="0"/>
			<element name="lifesteal" type="Q1:attribute" minOccurs="0"/>
			<element name="persistent" type="Q1:attribute" minOccurs="0"/>
			<element name="min_level" type="Q1:attribute" minOccurs="0"/>
			<element name="life_support" type="Q1:attribute" minOccurs="0"/>
			<element name="slot_name" type="Q1:attribute" minOccurs="0"/>
			<element name="undroppableondeath" type="Q1:attribute" minOccurs="0"/>
			<element name="autobind" type="Q1:attribute" minOccurs="0"/>
			<element name="slot_size" type="Q1:attribute" minOccurs="0"/>
			<element name="menu" type="Q1:attribute" minOccurs="0"/>
			<element name="durability" type="Q1:attribute" minOccurs="0" maxOccurs="1"/>
			<element name="status_resist" type="Q1:stresist" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="attribute">
		<attribute name="value" type="string"></attribute>
	</complexType>

	<complexType name="equipable">
		<sequence>
			<element name="slot" type="Q1:slot" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="slot">
		<attribute name="name" type="string"></attribute>
	</complexType>

	<complexType name="damage">
		<attribute name="type" type="string" />
	</complexType>

	<complexType name="susceptibility">
		<attribute name="type" type="string" />
		<attribute name="value" type="decimal" />
	</complexType>

	<complexType name="stresist">
		<attribute name="type" type="string" />
		<attribute name="value" type="decimal" />
		<attribute name="slots" type="string" />
	</complexType>

</schema>

=== arianne/stendhal/data/conf/items/tools.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../items.xsd">

  <item name="food mill">
    <type class="tool" subclass="foodmill" tileid="-1"/>
    <description>You see a food mill. It is the traditional tool to mill food.</description>
    <implementation class-name="games.stendhal.server.entity.item.FoodMill"/>
    <attributes>
      <menu value="Use|Use"/>
    </attributes>
    <weight value="10.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="sugar mill">
    <type class="tool" subclass="sugarmill" tileid="-1"/>
    <description>You see a sugar mill. You can obtain sugar if you grind canes with it.</description>
    <implementation class-name="games.stendhal.server.entity.item.FoodMill"/>
    <attributes>
      <menu value="Use|Use"/>
    </attributes>
    <weight value="10.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="scroll eraser">
    <type class="tool" subclass="scrolleraser" tileid="-1"/>
    <description>You see a scroll eraser. Put a marked scroll in the opposite hand to clean the scroll.</description>
    <implementation class-name="games.stendhal.server.entity.item.FoodMill"/>
    <attributes>
      <menu value="Use|Use"/>
    </attributes>
    <weight value="3.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="pestle and mortar">
    <type class="tool" subclass="pestleandmortar" tileid="-1"/>
    <description>You see a pestle and mortar. This is the traditional tool to pound herbs, food and other substances.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
    </attributes>
    <weight value="10.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="gold pan">
    <type class="tool" subclass="gold_pan" tileid="-1"/>
    <description>You see a gold pan. It is the traditional tool to prospect for gold.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
    </attributes>
    <weight value="10.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="fishing rod">
    <type class="tool" subclass="fishing_rod" tileid="-1"/>
    <description>You see a fishing rod. If you find a fishing spot you can catch fish with it.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
    </attributes>
    <weight value="10.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="lamp">
    <type class="tool" subclass="lamp" tileid="-1"/>
    <description>You see a lamp.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
    </attributes>
    <weight value="1.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="magical scissors">
    <type class="tool" subclass="magical_scissors" tileid="-1"/>
    <description>You see a sparkling pair of magical scissors. Just think what they could cut!</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
    </attributes>
    <weight value="3.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="magical needle">
    <type class="tool" subclass="magical_needle" tileid="-1"/>
    <description>You see a magical needle with a very sharp point.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
    </attributes>
    <weight value="0.5"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="pick">
    <type class="tool" subclass="pick" tileid="-1"/>
    <description>You see a pick. It is a tool which helps you to get some coal.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
    </attributes>
    <weight value="10.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="shovel">
    <type class="tool" subclass="shovel" tileid="-1"/>
    <description>You see a shovel, a tool for digging.</description>
    <implementation class-name="games.stendhal.server.entity.item.Shovel"/>
    <attributes>
      <menu value="Dig|Use"/>
      <use_sound value="shovel_dig"/>
    </attributes>
    <weight value="10.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="leather needle">
    <type class="tool" subclass="leather_needle" tileid="-1"/>
    <description>You see a heavy leather needle for working thick hide.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
    </attributes>
    <weight value="1.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="rotary cutter">
    <type class="tool" subclass="rotary_cutter" tileid="-1"/>
    <description>You see a rotary cutter. It can be used to cut up pizza. But perhaps it can be used on other things as well.</description>
    <implementation class-name="games.stendhal.server.entity.item.FoodMill"/>
    <attributes>
      <menu value="Use|Use"/>
    </attributes>
    <weight value="1.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

  <item name="metal detector">
    <type class="tool" subclass="metal_detector" tileid="-1"/>
    <description></description>
    <implementation class-name="games.stendhal.server.entity.item.MetalDetector"/>
    <attributes>
      <menu value="Scan|Use"/>
    </attributes>
    <weight value="10.0"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
    </equipable>
  </item>

</items>

=== arianne/stendhal/data/conf/items/money.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../items.xsd">

  <item name="money">
    <type class="money" subclass="gold" tileid="-1"/>
    <description/>
    <implementation class-name="games.stendhal.server.entity.item.Money"/>
    <attributes>
      <quantity value="1"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="pouch"/>
    </equipable>
  </item>

</items>

=== arianne/stendhal/data/conf/items/ranged.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">
  <item name="wooden bow">
    <type class="ranged" subclass="wooden_bow" tileid="-1"/>
    <description>You see a wooden bow. With this in one hand, and wooden arrows in the other, you may be able to attack from a distance.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
      <ratk value="12"/>
      <range value="3"/>
    </attributes>
    <weight value="1.0"/>
    <value value="17280"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="longbow">
    <type class="ranged" subclass="longbow" tileid="-1"/>
    <description>You see a longbow. Equipped with this, and a supply of arrows, you will have an effective ranged attack.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
      <ratk value="14"/>
      <range value="4"/>
    </attributes>
    <weight value="1.0"/>
    <value value="27440"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="composite bow">
    <type class="ranged" subclass="composite_bow" tileid="-1"/>
    <description>You see a composite bow. It's better strung than most bows, for excellent ranged attack.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
      <ratk value="15"/>
      <range value="5"/>
    </attributes>
    <weight value="1.0"/>
    <value value="33750"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="crossbow">
    <type class="ranged" subclass="crossbow" tileid="-1"/>
 <description>You see a crossbow. The attack is high but it has a very short range, what do you prefer?</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
      <ratk value="17"/>
      <range value="3"/>
    </attributes>
    <weight value="3.0"/>
    <value value="49130"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="hunter crossbow">
    <type class="ranged" subclass="hunter_crossbow" tileid="-1"/>
 <description>You see a hunter crossbow. You must decide if the high attack is worth the short range it has.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
      <ratk value="21"/>
      <range value="4"/>
    </attributes>
    <weight value="3.0"/>
    <value value="92610"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

    <item name="mithril bow">
    <type class="ranged" subclass="mithril_bow" tileid="-1"/>
   <description>You see a light and strong mithril bow. Its impeccable workmanship affords incredible accuracy.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
      <ratk value="28"/>
      <range value="4"/>
    </attributes>
    <weight value="3.0"/>
    <value value="142610"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

</items>

=== arianne/stendhal/data/conf/items/books.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../items.xsd">

  <item name="black book">
    <type class="book" subclass="book_black" tileid="-1"/>
    <description>You see the black book that Jynath kept out for so long.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="blue book">
    <type class="book" subclass="book_blue" tileid="-1"/>
    <description>You see a book with the words GEMS AND MINERALS on the front cover.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="bestiary">
    <type class="book" subclass="bestiary" tileid="-1"/>
    <description>You see a bestiary, containing information about enemies found in Faiumoni.</description>
    <implementation class-name="games.stendhal.server.entity.item.Bestiary"/>
    <attributes>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

</items>

=== arianne/stendhal/data/conf/items/flowers.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../items.xsd">

  <item name="rhosyd">
    <type class="flower" subclass="exotic_flower" tileid="-1"/>
    <description>You see a beautiful and rare rhosyd flower.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="rose">
    <type class="flower" subclass="rose" tileid="-1"/>
    <description>You see a single red rose. It smells heavenly.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="lilia">
    <type class="flower" subclass="lilia" tileid="-1"/>
    <description>You see a lilia, a single precious bloom.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="daisies">
    <type class="flower" subclass="daisies" tileid="-1"/>
    <description>You see a bunch of daisies. They are cheap and cheerful!</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="pansy">
    <type class="flower" subclass="pansy" tileid="-1"/>
    <description>You see a pansy, so colorful and beautiful.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

  <item name="zantedeschia">
    <type class="flower" subclass="zantedeschia" tileid="-1"/>
    <description>You see a zantedeschia, a delicate bloom with the sweetest fragrance.</description>
    <implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
    <attributes>
      <quantity value="1"/>
      <max_quantity value="2147483647"/>
    </attributes>
    <weight value="0.01"/>
    <value value="1"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="lhand"/>
      <slot name="rhand"/>
      <slot name="bag"/>
      <slot name="trade"/>
    </equipable>
  </item>

</items>

=== arianne/stendhal/data/conf/items/legs.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">
  <item name="leather legs">
    <type class="legs" subclass="leather_legs" tileid="-1"/>
    <description>You see a pair of leather legs. They look new but they're poor quality.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="1"/>
    </attributes>
    <weight value="10.0"/>
    <value value="7"/>
    <equipable>
      <slot name="legs"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="studded legs">
    <type class="legs" subclass="studded_legs" tileid="-1"/>
    <description>You see a pair of blood stained studded legs. You're not sure if the blood came from their last owner ... or his enemies.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="2"/>
    </attributes>
    <weight value="12.0"/>
    <value value="56"/>
    <equipable>
      <slot name="legs"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="chain legs">
    <type class="legs" subclass="chain_legs" tileid="-1"/>
    <description>You see a pair of well made chain legs. They should protect you against any attacks aimed low.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="4"/>
    </attributes>
    <weight value="15.0"/>
    <value value="448"/>
    <equipable>
      <slot name="legs"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="red legs">
    <type class="legs" subclass="red_legs" tileid="-1"/>
    <description>A pair of red legs are in your grasp.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="5"/>
    </attributes>
    <weight value="12.0"/>
    <value value="1512"/>
    <equipable>
      <slot name="legs"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="elvish legs">
    <type class="legs" subclass="elvish_legs" tileid="-1"/>
    <description>You see a pair of elvish legs.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="6"/>
    </attributes>
    <weight value="12.0"/>
    <value value="1512"/>
    <equipable>
      <slot name="legs"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="blue legs">
    <type class="legs" subclass="blue_legs" tileid="-1"/>
    <description>You see a pair of shiny new blue legs.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="7"/>
    </attributes>
    <weight value="12.0"/>
    <value value="1512"/>
    <equipable>
      <slot name="legs"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="golden legs">
    <type class="legs" subclass="golden_legs" tileid="-1"/>
    <description>You see a pair of shining, strong golden legs.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="8"/>
    </attributes>
    <weight value="25.0"/>
    <value value="3584"/>
    <equipable>
      <slot name="legs"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="shadow legs">
    <type class="legs" subclass="shadow_legs" tileid="-1"/>
    <description>You see a pair of shadow legs. The weight of them is incredible.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="9"/>
    </attributes>
    <weight value="25.0"/>
    <value value="5103"/>
    <susceptibility type="light" value="1.4"/>
    <susceptibility type="dark" value="0.9"/>
    <equipable>
      <slot name="legs"/>
      <slot name="bag"/>
    </equipable>
  </item>

  <item name="mainio legs">
    <type class="legs" subclass="mainio_legs" tileid="-1"/>
    <description>You see a pair of odd looking mainio legs. They are somewhat startling but they give you a good protection.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="10"/>
    </attributes>
    <weight value="25.0"/>
    <value value="7317"/>
    <equipable>
      <slot name="bag"/>
      <slot name="legs"/>
    </equipable>
  </item>

  <item name="chaos legs">
    <type class="legs" subclass="chaos_legs" tileid="-1"/>
    <description>You see a pair of chaos legs. The strange colours confuse you.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="11"/>
    </attributes>
    <weight value="25.0"/>
    <value value="9317"/>
    <equipable>
      <slot name="bag"/>
      <slot name="legs"/>
    </equipable>
  </item>

  <item name="xeno legs">
    <type class="legs" subclass="xeno_legs" tileid="-1"/>
    <description>You see a pair of xeno legs. They're very strong and look brand new.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="11"/>
    </attributes>
    <weight value="25.0"/>
    <value value="10017"/>
    <equipable>
      <slot name="bag"/>
      <slot name="legs"/>
    </equipable>
  </item>

  <item name="jewelled legs">
    <type class="legs" subclass="jewelled_legs" tileid="-1"/>
    <description>You see a beautiful pair of jewelled legs. A large red gem glints at you and they're encrusted all over with sapphires.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="13"/>
    </attributes>
    <weight value="25.0"/>
    <value value="15017"/>
    <equipable>
      <slot name="bag"/>
      <slot name="legs"/>
    </equipable>
  </item>

  <item name="black legs">
    <type class="legs" subclass="black_legs" tileid="-1"/>
    <description>You see a pair of black legs.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="15"/>
    </attributes>
    <weight value="25.0"/>
    <value value="23625"/>
    <susceptibility type="light" value="1.2"/>
    <susceptibility type="dark" value="0.95"/>
    <equipable>
      <slot name="bag"/>
      <slot name="legs"/>
    </equipable>
  </item>

  <item name="mithril legs">
    <type class="legs" subclass="mithril_legs" tileid="-1"/>
    <description>You see a pair of mithril legs. They will serve you well.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>    <attributes>
      <def value="18"/>
    </attributes>
    <weight value="22.0"/>
    <value value="53625"/>
    <susceptibility type="light" value="0.9"/>
    <susceptibility type="dark" value="1.3"/>
    <equipable>
      <slot name="bag"/>
      <slot name="legs"/>
    </equipable>
  </item>
</items>
