=== arianne/stendhal/data/conf/shops.xsd
<?xml version="1.0"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
    xmlns:tns="http://www.example.org/shops" elementFormDefault="qualified"
    xmlns:Q2="stendhal">

  <element name="shops" type="Q2:ShopGroup"/>

  <complexType name="ShopGroup">
    <sequence>
      <element name="shop" type="Q2:Shop" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <complexType name="Shop">
    <sequence>
      <choice minOccurs="1" maxOccurs="1">
        <sequence>
          <element name="item" type="Q2:ShopItem" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
        <sequence>
          <element name="outfit" type="Q2:OutfitItem" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
      </choice>
      <element name="merchant" type="Q2:Merchant" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <!-- "name" can be omitted if shop is listed for website reading only -->
    <attribute name="name" type="string" use="optional"/>
    <attribute name="type" type="Q2:ShopType" use="required"/>
    <attribute name="condition" type="string" use="optional"/>
  </complexType>

  <simpleType name="ShopType">
    <restriction base="string">
      <enumeration value="buy"/>
      <enumeration value="sell"/>
      <enumeration value="trade"/>
      <enumeration value="outfit"/>
    </restriction>
  </simpleType>

  <complexType name="BaseItem">
    <sequence>
      <element name="for" type="Q2:TradeFor" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="name" type="string" use="required"/>
    <attribute name="note" type="string" use="optional"/>
  </complexType>

  <complexType name="ShopItem">
    <complexContent>
      <extension base="Q2:BaseItem">
        <attribute name="price" type="int" use="optional"/>
        <attribute name="pricemax" type="int" use="optional"/>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="OutfitItem">
    <complexContent>
      <extension base="Q2:BaseItem">
        <attribute name="price" type="int" use="required"/>
        <attribute name="layers" type="string" use="required"/>
      </extension>
    </complexContent>
  </complexType>

  <!-- items required for purchase other than money -->
  <complexType name="TradeFor">
    <attribute name="name" type="string" use="required"/>
    <attribute name="count" type="string" use="required"/>
  </complexType>

  <!--
    Merchant flags are a comma-separated string.
    Valid merchant flags are:
      * configure:  XML loader will configure NPC for shop at startup.
      * noOffer:    Will not add default replies to "offer".
      * returnable: Outfits can be returned to vendor.
      * resetOrig:  Temporary outfits will be reset to original before updating.
  -->

  <complexType name="Merchant">
    <attribute name="name" type="string" use="required"/>
    <attribute name="flags" type="string" use="optional"/>
    <!-- used by website only -->
    <attribute name="note" type="string" use="optional"/>
    <!-- defaults to "buy" if not set (outfits) -->
    <attribute name="action" type="string" use="optional"/>
    <!-- default is to never expire (outfits) -->
    <attribute name="expires" type="int" use="optional"/>
    <attribute name="wearOffMessage" type="string" use="optional"/>
  </complexType>

</schema>

=== arianne/stendhal/data/conf/shops/sell_outfits.xml
<?xml version="1.0" encoding="UTF-8"?>

<shops xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../shops.xsd">

  <!-- OUTFIT SELLERS/LENDERS -->

  <!--
    Merchant flags descriptions:
      configure: merchant will be configured at startup with shop
      noOffer: disable default replies to "offer"
      removeDetailColor: do not preserve detail color when changing outfit
      resetBeforeChange: remove temp outfit & restore original before change
  -->

  <shop name="deniran_accessories" type="outfit">
    <outfit name="white balloon" layers="detail=2" price="50000"/>
    <outfit name="black balloon" layers="detail=3" price="50000"/>
    <outfit name="bone" layers="detail=4" price="100000"/>
    <outfit name="umbrella" layers="detail=7" price="50000"/>
    <outfit name="sword" layers="detail=8" price="250000"/>
    <outfit name="knife" layers="detail=9" price="125000"/>
    <outfit name="spear" layers="detail=10" price="150000"/>
    <outfit name="bow" layers="detail=11" price="175000"/>
    <outfit name="axe1" layers="detail=12" price="250000"/>
    <outfit name="axe2" layers="detail=13" price="250000"/>
    <outfit name="kite shield" layers="detail=14" price="225000"/>
    <outfit name="shield" layers="detail=15" price="225000"/>
    <merchant name="Gwen" flags="configure,noOffer,removeDetailColor"/>
  </shop>

  <!-- Pierre in Deniran Dress Shop -->
  <shop type="outfit">
    <outfit name="blue bear" layers="hat=993" price="2500"/>
    <outfit name="brown bear" layers="hat=994" price="2500"/>
    <outfit name="superstendhal" layers="dress=973,hat=992" price="5000"/>
    <merchant name="Pierre"/>
  </shop>

  <!-- Liliana in Magic Clothing Boutique -->
  <shop type="outfit">
    <outfit name="jumpsuit" layers="dress=983" price="500"/>
    <outfit name="dungarees" layers="dress=984" price="500"/>
    <outfit name="green dress" layers="dress=978" price="500"/>
    <outfit name="gown" layers="dress=982" price="750"/>
    <outfit name="orange" layers="dress=980" price="500"/>
    <outfit name="bunny" layers="dress=981" price="800"/>
    <outfit name="jester" layers="dress=976,hat=995" price="400"/>
    <outfit name="horse" layers="body=997" price="1200"/>
    <outfit name="girl horse" layers="body=996" price="1200"/>
    <outfit name="alien" layers="body=995" price="1200"/>
    <merchant name="Liliana"/>
  </shop>

  <!-- Saski in Magic Clothing Boutique -->
  <shop type="outfit">
    <outfit name="goblin face" layers="head=988" price="500"/>
    <outfit name="thing face" layers="head=987" price="500"/>
    <outfit name="purple slime" layers="body=993" price="3000"/>
    <outfit name="green slime" layers="body=989" price="3000"/>
    <outfit name="red slime" layers="body=988" price="3000"/>
    <outfit name="blue slime" layers="body=991" price="3000"/>
    <outfit name="gingerbread man" layers="body=992" price="1200"/>
    <outfit name="white cat" layers="body=978" price="4500"/>
    <outfit name="black cat" layers="body=979" price="4500"/>
    <merchant name="Saskia"/>
  </shop>

</shops>
