=== arianne/stendhal/data/conf/zones.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
		xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
		xmlns:Q1="stendhal">

	<complexType name="zone">
		<annotation>
			<documentation>
				a zone can have 0 to many configurators
			</documentation>
		</annotation>
		<sequence>
			<element name="title" type="string" minOccurs="0" maxOccurs="1"/>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element name="attributes" type="Q1:attributeGroup"
					minOccurs="0" maxOccurs="unbounded"/>
				<element name="configurator" type="Q1:configurator"
					minOccurs="0" maxOccurs="unbounded"/>
				<element name="point-of-interest" type="Q1:point-of-interest" minOccurs="0"
					maxOccurs="unbounded"/>
				<element name="portal" type="Q1:portal" minOccurs="0"
					maxOccurs="unbounded"/>
				<element name="entity" type="Q1:entity" minOccurs="0"
					maxOccurs="unbounded"/>
				<element name="associated" type="Q1:associatedZones" minOccurs="0"
					maxOccurs="1"/>
				<element name="spawns" type="Q1:spawnsGroup" minOccurs="0" maxOccurs="1"/>
			</choice>
		</sequence>
		<attribute name="name" type="string"/>
		<attribute name="x" type="int" use="optional"/>
		<attribute name="y" type="int" use="optional"/>
		<attribute name="accessible" type="boolean" use="optional" default="true"/>
		<attribute name="level" type="int" use="optional"/>
		<attribute name="file" type="string" use="required"/>
	</complexType>

	<complexType name="zones">
		<sequence>
			<element name="zone" type="Q1:zone" maxOccurs="unbounded"
				minOccurs="0">
			</element>
		</sequence>
	</complexType>

	<element name="zones" type="Q1:zones"></element>

	<complexType name="point-of-interest">
		<sequence minOccurs="1" maxOccurs="1">
			<element name="name" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="title" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="type" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="description" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="url" type="string" minOccurs="0" maxOccurs="1"/>
		</sequence>
		<attribute name="x" type="int"></attribute>
		<attribute name="y" type="int"></attribute>
		<attribute name="condition" type="string" use="optional"></attribute>
	</complexType>

	<complexType name="attributeGroup">
		<sequence>
			<element name="parameter" type="Q1:parameterType" minOccurs="1"
				maxOccurs="unbounded">
			</element>
		</sequence>
		<attribute name="condition" type="string" use="optional"></attribute>
	</complexType>

	<complexType name="portal">
		<sequence minOccurs="1" maxOccurs="1">
			<element name="destination" type="Q1:destination" minOccurs="0"
				maxOccurs="1">
			</element>
			<element name="implementation" type="Q1:implementation"
				minOccurs="0" maxOccurs="1"/>
			<element name="attribute" type="Q1:attributeType"
					minOccurs="0" maxOccurs="unbounded"/>
			<element name="associated" type="Q1:associatedZones"
				minOccurs="0" maxOccurs="1"/>
		</sequence>
		<attribute name="x" type="int"></attribute>
		<attribute name="y" type="int"></attribute>
		<attribute name="ref" type="string"></attribute>
		<attribute name="replacing" type="boolean"></attribute>
		<attribute name="condition" type="string"></attribute>
	</complexType>
	<complexType name="configurator">
		<sequence>
			<element name="parameter" type="Q1:parameterType" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="class-name" type="string"></attribute>
		<attribute name="condition" type="string" use="optional"></attribute>
	</complexType>

	<complexType name="destination">
		<sequence></sequence>
		<attribute name="zone" type="string"></attribute>
		<attribute name="ref" type="string"></attribute>
	</complexType>

	<complexType name="parameterType">
		<simpleContent>
			<extension base="string">
				<attribute name="name" type="string"></attribute>
				<attribute name="condition" type="string" use="optional"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="ConfiguratorGroup">
		<sequence>
			<element name="configurator" type="Q1:configurator"
				minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="condition" type="string" use="optional"></attribute>
	</complexType>


	<complexType name="portals">
		<sequence>
			<element name="portal" type="Q1:portal" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>


	<complexType name="implementation">
		<sequence>
			<element name="attribute" type="Q1:attributeType" minOccurs="0"/>
			<element name="parameter" type="Q1:parameterType" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="class-name" type="string"></attribute>
	</complexType>

	<complexType name="port">
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="expression" type="string" use="optional"></attribute>
	</complexType>

	<complexType name="connector">
		<sequence>
			<element name="port" type="Q1:port"
				minOccurs="0" maxOccurs="unbounded">
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>

	<complexType name="entity">
		<sequence>
			<element name="implementation" type="Q1:implementation"
				minOccurs="1" maxOccurs="1">
			</element>
			<element name="connector" type="Q1:connector"
				minOccurs="0" maxOccurs="1">
			</element>
			<element name="attribute" type="Q1:attributeType"
				minOccurs="0" maxOccurs="unbounded">
			</element>
		</sequence>
		<attribute name="x" type="int"></attribute>
		<attribute name="y" type="int"></attribute>
		<attribute name="condition" type="string" use="optional"></attribute>
	</complexType>

	<complexType name="attributeType">
		<simpleContent>
			<extension base="string">
				<attribute name="name" type="string"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="associatedZones">
		<attribute name="zones" type="string" use="required"></attribute>
	</complexType>

	<complexType name="spawnsGroup">
		<choice minOccurs="1" maxOccurs="unbounded">
			<element name="creatures" type="Q1:creaturesSpawnsGroup" minOccurs="0" maxOccurs="1"/>
		</choice>
	</complexType>

	<!--
		adding a dynamic creature spawner to zone:
			<spawns>
				<creatures>
					<parameter name="bat">15</parameter>
				</creatures>
			</spans> 

		"name" attribute is the creature to be spawned, value is the maximum number that can be active
		at same time
	-->
	<complexType name="creaturesSpawnsGroup">
		<sequence>
			<element name="parameter" type="Q1:parameterType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>

</schema>

=== arianne/stendhal/data/conf/zones/amazon.xml
<?xml version="1.0" encoding="UTF-8"?>
<zones xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../zones.xsd ">
 <!--
   ** Load zones. Written from left to right and from top to bottom.
   ** Please respect it!
   -->


 <!--  Level 6 -->


 <!--  Level 5 -->


 <!--  Level 4 -->


 <!--  Level 3 -->


 <!--  Level 2 -->


 <!--  Level 1 -->


 <!--  Ground level -->
 <zone name="int_amazon_princess_hut" file="interiors/amazon/princess_hut.tmx">
 <configurator class-name="games.stendhal.server.maps.amazon.hut.PrincessNPC"/>
  <portal x="10" y="18" ref="out">
   <destination zone="0_amazon_island_ne" ref="in"/>
  </portal>
 </zone>

 <zone name="int_amazon_prison_hut" file="interiors/amazon/prison_hut.tmx">
 <configurator class-name="games.stendhal.server.maps.amazon.hut.JailedBarbNPC"/>
  <portal x="7" y="14" ref="out">
   <destination zone="0_amazon_island_sw" ref="in"/>
  </portal>
 </zone>

 <zone name="0_amazon_island_nw" level="0" x="501024" y="499744" file="Level 0/amazon/island_nw.tmx">
 </zone>

 <zone name="0_amazon_island_ne" level="0" x="501152" y="499744" file="Level 0/amazon/island_ne.tmx">
  <configurator class-name="games.stendhal.server.maps.amazon.fleamarket.AmazonMermaidArmorNPC"/>
 <entity x="11" y="81">
     <implementation class-name="games.stendhal.server.entity.mapstuff.sign.Sign"/>
     <attribute name="text">
I buy good, quality cloaks:

elf cloak  50
lich cloak  10000
xeno cloak  18000
stone cloak  350
vampire cloak  14000
red dragon cloak  4000
blue striped cloak 280
     </attribute>
     <attribute name="class">blackboard</attribute>
    </entity>
  <portal x="48" y="98" ref="in">
   <destination zone="int_amazon_princess_hut" ref="out"/>
  </portal>
 </zone>

 <zone name="0_amazon_island_sw" level="0" x="501024" y="499872" file="Level 0/amazon/island_sw.tmx">
  <portal x="64" y="26" ref="in">
   <destination zone="int_amazon_prison_hut" ref="out"/>
  </portal>
 </zone>

 <zone name="0_amazon_island_se" level="0" x="501152" y="499872" file="Level 0/amazon/island_se.tmx">
 </zone>

  <!--  Level -1 -->
 <zone name="-1_amazon_caves" level="-1" x="501152" y="499744" file="Level -1/amazon/caves.tmx">
 </zone>

 <zone name="-1_amazon_tunnel_e" level="-1" x="501024" y="499744" file="Level -1/amazon/tunnel_e.tmx">
 </zone>

 <zone name="-1_amazon_tunnel" level="-1" x="500896" y="499744" file="Level -1/amazon/tunnel.tmx">
 </zone>
 
 <!--  Level -2 -->


 <!--  Level -3 -->


 <!--  Level -4 -->


 <!--  Level -5 -->


 <!--  Level -6 -->


 <!--  Level -7 -->

</zones>

=== arianne/stendhal/data/conf/zones/kikareukin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE zones SYSTEM "zones.dtd"> -->
<zones xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal zones.xsd ">
 <!--
   ** Load zones. Written from left to right and from top to bottom.
   ** Please respect it!
   -->

 <!-- Level 7 -->

 <zone name="7_kikareukin_clouds" level="7" x="499616" y="499744" file="Level 7/kikareukin/clouds.tmx">
<!--Don't allow teleporting as we don't want marked scrolls made or ring abused-->
  <configurator class-name="games.stendhal.server.core.config.zone.NoTeleport"/>
  <portal x="29" y="6" ref="exit1">
   <destination zone="6_kikareukin_islands" ref="cloud_exit1"/>
  </portal>
  <portal x="9" y="47" ref="exit2">
   <destination zone="6_kikareukin_islands" ref="cloud_exit2"/>
  </portal>
  <portal x="51" y="18" ref="exit3">
   <destination zone="6_kikareukin_islands" ref="cloud_exit3"/>
  </portal>
 </zone>

 <!-- Level 6 -->

 <zone name="6_kikareukin_islands" level="6" x="499616" y="499744" file="Level 6/kikareukin/islands.tmx">
  <portal x="66" y="63" ref="exit">
   <destination zone="0_semos_mountain_n_w4" ref="kikareukin_exit"/>
  </portal>
  <portal x="25" y="8" ref="cloud_exit1">
   <implementation class-name="games.stendhal.server.entity.mapstuff.portal.OneWayPortalDestination"/>
  </portal>
  <portal x="6" y="110" ref="cloud_exit2">
   <implementation class-name="games.stendhal.server.entity.mapstuff.portal.OneWayPortalDestination"/>
  </portal>
  <portal x="93" y="9" ref="cloud_exit3">
   <implementation class-name="games.stendhal.server.entity.mapstuff.portal.OneWayPortalDestination"/>
  </portal>
 </zone>


 <!-- Level 5 -->

 <zone name="5_kikareukin_cave" level="5" x="499616" y="499744" file="Level 5/kikareukin/cave.tmx">
 </zone>


 <!-- Level 4 -->

 <zone name="4_kikareukin_cave" level="4" x="499616" y="499744" file="Level 4/kikareukin/cave.tmx">
 </zone>


 <!-- Level 3 -->

 <zone name="3_kikareukin_cave" level="3" x="499616" y="499744" file="Level 3/kikareukin/cave.tmx">
 </zone>


 <!-- Level 2 -->

 <zone name="2_kikareukin_cave" level="2" x="499616" y="499744" file="Level 2/kikareukin/cave.tmx">
 </zone>


 <!-- Level 1 -->

 <zone name="1_kikareukin_cave" level="1" x="499616" y="499744" file="Level 1/kikareukin/cave.tmx">
  <portal x="16" y="96" ref="entrance">
   <destination zone="0_semos_mountain_n_w4" ref="kikareukin_entrance"/>
  </portal>
 </zone>


 <!-- Level 0 (Ground) -->


 <!-- Level -1 -->


 <!-- Level -2 -->


 <!-- Level -3 -->


 <!-- Level -4 -->


 <!-- Level -5 -->


 <!-- Level -6 -->


 <!-- Level -7 -->

</zones>

=== arianne/stendhal/data/conf/zones/misc.xml
<?xml version="1.0" encoding="UTF-8"?>

<zones xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="stendhal ../zones.xsd ">

  <zone name="int_afterlife" file="interiors/abstract/afterlife.tmx">
    <attributes>
      <parameter name="color_method">softlight</parameter>
      <parameter name="color">#008888</parameter>
    </attributes>
    <portal x="30" y="6" ref="exit_left">
      <destination zone="int_semos_temple" ref="restart_life" />
    </portal>

    <portal x="31" y="6" ref="exit_center">
      <destination zone="int_semos_temple" ref="restart_life" />
    </portal>

    <portal x="32" y="6" ref="exit_right">
      <destination zone="int_semos_temple" ref="restart_life" />
    </portal>

    <entity x="29" y="22">
      <implementation class-name="games.stendhal.server.entity.mapstuff.sign.Sign" />
      <attribute name="text">
You are a ghost in the afterlife.

Walk on, and you will be returned to the land of the living...
			</attribute>
    </entity>

    <entity x="33" y="22">
      <implementation class-name="games.stendhal.server.entity.mapstuff.sign.Sign" />
      <attribute name="text">
You are a ghost in the afterlife.

Walk on, and you will be returned to the land of the living...
				</attribute>
    </entity>
  </zone>

  <zone name="int_admin_playground" file="interiors/abstract/admin_playground.tmx"
    accessible="false">
  </zone>

  <zone name="int_abstract_server_down" file="interiors/abstract/server_down.tmx"
    accessible="false">
    <configurator class-name="games.stendhal.server.core.config.zone.NoTeleport" />
    <configurator class-name="games.stendhal.server.core.config.zone.NoItemMove">
      <parameter name="message">You should keep your items safe for now.</parameter>
    </configurator>

    <!-- Note: This portal is defined in ServerDown, too. -->
    <portal x="15" y="28" ref="exit">
      <destination zone="0_semos_city" ref="townhall_entrance" />
    </portal>

    <entity x="0" y="0">
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.sound.BackgroundMusicSource">
        <parameter name="sound">a_weird_place</parameter>
        <parameter name="volume">50</parameter>
      </implementation>
    </entity>
  </zone>

  <zone name="int_abstract_admin_investigation" file="interiors/abstract/admin_investigation.tmx">
    <configurator class-name="games.stendhal.server.core.config.zone.NoTeleport" />
    <portal x="6" y="10" ref="entrance1">
      <destination zone="int_semos_temple" ref="restart_life" />
    </portal>
    <portal x="19" y="10" ref="entrance2">
      <destination zone="int_semos_temple" ref="restart_life" />
    </portal>

    <entity x="16" y="2">
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.chest.PersonalChest">
        <parameter name="slot">bank_nalwor</parameter>
      </implementation>
    </entity>
    <entity x="17" y="2">
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.chest.PersonalChest">
        <parameter name="slot">bank</parameter>
      </implementation>
    </entity>
    <entity x="18" y="2">
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.chest.PersonalChest">
        <parameter name="slot">bank_ados</parameter>
      </implementation>
    </entity>
    <entity x="16" y="3">
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.chest.PersonalChest">
        <parameter name="slot">bank_fado</parameter>
      </implementation>
    </entity>
    <entity x="18" y="3">
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.chest.PersonalChest">
        <parameter name="slot">zaras_chest_ados</parameter>
      </implementation>
    </entity>

    <entity x="20" y="2">
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.chest.PersonalChest">
        <parameter name="slot">bank_nalwor</parameter>
      </implementation>
    </entity>
    <entity x="21" y="2">
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.chest.PersonalChest">
        <parameter name="slot">bank</parameter>
      </implementation>
    </entity>
    <entity x="22" y="2">
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.chest.PersonalChest">
        <parameter name="slot">bank_ados</parameter>
      </implementation>
    </entity>
    <entity x="20" y="3">
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.chest.PersonalChest">
        <parameter name="slot">bank_fado</parameter>
      </implementation>
    </entity>
    <entity x="22" y="3">
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.chest.PersonalChest">
        <parameter name="slot">zaras_chest_ados</parameter>
      </implementation>
    </entity>
  </zone>

  <zone name="int_testing_grid" file="interiors/abstract/testing_grid.tmx"
    accessible="false">
  </zone>

  <zone name="int_vault" file="interiors/abstract/vault.tmx"
    accessible="false">
  </zone>

  <zone name="int_adventure_island" file="interiors/abstract/adventure_island.tmx"
    accessible="false">
  </zone>

  <zone name="int_pathfinding" file="interiors/abstract/pathfinding.tmx"
    accessible="false">

    <configurator class-name="games.stendhal.server.maps.FeaturesTestArea" />

    <portal x="50" y="10" ref="locked_outside">
      <destination zone="int_pathfinding" ref="locked_inside" />
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.portal.LockedDoor">
        <parameter name="class">skulldoor_s</parameter>
        <parameter name="key">golden key</parameter>
      </implementation>
    </portal>

    <portal x="50" y="12" ref="locked_inside">
      <destination zone="int_pathfinding" ref="locked_outside" />
    </portal>

    <!-- volume -->
    <entity x="10" y="56">
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.sound.PeriodicAmbientSoundSource">
        <parameter name="sound">bird-2b</parameter>
        <parameter name="min">5</parameter>
        <parameter name="max">5</parameter>
        <parameter name="radius">4</parameter>
        <parameter name="volume">100</parameter>
      </implementation>
    </entity>
    <entity x="24" y="56">
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.sound.PeriodicAmbientSoundSource">
        <parameter name="sound">bird-2b</parameter>
        <parameter name="min">5</parameter>
        <parameter name="max">5</parameter>
        <parameter name="radius">4</parameter>
        <parameter name="volume">40</parameter>
      </implementation>
    </entity>

    <!-- periodic and loop -->
    <entity x="42" y="56">
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.sound.PeriodicAmbientSoundSource">
        <parameter name="sound">bird-1b, bird-2b, bird-3b</parameter>
        <parameter name="min">5</parameter>
        <parameter name="max">10</parameter>
        <parameter name="radius">4</parameter>
      </implementation>
    </entity>
    <entity x="56" y="56">
      <implementation
        class-name="games.stendhal.server.entity.mapstuff.sound.LoopedAmbientSoundSource">
        <parameter name="sound">wind-2</parameter>
        <parameter name="volume">40</parameter>
        <parameter name="radius">4</parameter>
      </implementation>
    </entity>
  </zone>

</zones>

=== arianne/stendhal/data/conf/zones/sikhw.xml
<?xml version="1.0" encoding="UTF-8"?>

<zones xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="stendhal ../zones.xsd">

  <!-- ** Load zones. Written from left to right and from top to bottom. **
    Please respect it! -->

  <!-- Ground level -->

  <zone name="0_sikhw_desert_n_w2" level="0" x="499104" y="500384"
      file="Level 0/sikhw/desert_n_w2.tmx">

      <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>

  </zone>


  <zone name="0_sikhw_desert_w2" level="0" x="499104" y="500512"
    file="Level 0/sikhw/desert_w2.tmx">

    <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>

  </zone>


  <zone name="0_sikhw_desert_s_w2" level="0" x="499104" y="500640"
    file="Level 0/sikhw/desert_s_w2.tmx">

    <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>

  </zone>


  <zone name="0_sikhw_desert_s2_w2" level="0" x="499104" y="500768"
    file="Level 0/sikhw/desert_s2_w2.tmx">

    <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>

  </zone>


  <!--   -->

  <zone name="0_sikhw_desert_nw" level="0" x="499232" y="500384"
    file="Level 0/sikhw/desert_nw.tmx">

    <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>

  </zone>


  <zone name="0_sikhw_desert_w" level="0" x="499232" y="500512"
      file="Level 0/sikhw/desert_w.tmx">

      <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>

  </zone>


  <zone name="0_sikhw_desert_sw" level="0" x="499232" y="500640"
    file="Level 0/sikhw/desert_sw.tmx">

    <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>

  </zone>


  <zone name="0_sikhw_desert_s2_w" level="0" x="499232" y="500768"
    file="Level 0/sikhw/desert_s2_w.tmx">

    <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>

  </zone>


  <!--   -->

  <zone name="0_sikhw_desert_n" level="0" x="499360" y="500384"
    file="Level 0/sikhw/desert_n.tmx">

    <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>


  </zone>


  <zone name="0_sikhw_city" level="0" x="499360" y="500512"
    file="Level 0/sikhw/city.tmx">

    <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>

  </zone>


  <zone name="0_sikhw_desert_s" level="0" x="499360" y="500640"
    file="Level 0/sikhw/desert_s.tmx">

    <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>

  </zone>


  <zone name="0_sikhw_desert_s2" level="0" x="499360" y="500768"
    file="Level 0/sikhw/desert_s2.tmx">

    <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>

  </zone>


  <!--   -->

  <zone name="0_sikhw_desert_ne" level="0" x="499488" y="500384"
    file="Level 0/sikhw/desert_ne.tmx">

    <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>

  </zone>


  <zone name="0_sikhw_desert_e" level="0" x="499488" y="500512"
    file="Level 0/sikhw/desert_e.tmx">

    <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>

  </zone>


  <zone name="0_sikhw_desert_se" level="0" x="499488" y="500640"
    file="Level 0/sikhw/desert_se.tmx">

    <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>

  </zone>

  <zone name="0_sikhw_desert_s2_e" level="0" x="499488" y="500768"
    file="Level 0/sikhw/desert_s2_e.tmx">

    <attributes>
      <parameter name="color_method">time</parameter>
      <parameter name="weather">varying</parameter>
    </attributes>

  </zone>

</zones>
